from app.models.act_catalog import ActCatalog
from app.models.case import Case
from app.models.case_act import CaseAct
from app.models.case_act_data import CaseActData
from app.models.case_client_comment import CaseClientComment
from app.models.case_document import CaseDocument
from app.models.case_document_version import CaseDocumentVersion
from app.models.case_internal_note import CaseInternalNote
from app.models.case_participant import CaseParticipant
from app.models.case_state_definition import CaseStateDefinition
from app.models.case_timeline_event import CaseTimelineEvent
from app.models.case_workflow_event import CaseWorkflowEvent
from app.models.document_template import DocumentTemplate
from app.models.legal_entity import LegalEntity
from app.models.legal_entity_representative import LegalEntityRepresentative
from app.models.notary import Notary
from app.models.notary_commercial_activity import NotaryCommercialActivity
from app.models.notary_crm_audit_log import NotaryCrmAuditLog
from app.models.numbering_sequence import NumberingSequence
from app.models.person import Person
from app.models.role import Role
from app.models.role_assignment import RoleAssignment
from app.models.role_permission import RolePermission
from app.models.template_field import TemplateField
from app.models.template_required_role import TemplateRequiredRole
from app.models.user import User
