from app.models import (
    Case,
    CaseActData,
    CaseClientComment,
    CaseDocument,
    CaseDocumentVersion,
    CaseInternalNote,
    CaseParticipant,
    CaseStateDefinition,
    CaseTimelineEvent,
    CaseWorkflowEvent,
    DocumentTemplate,
    Notary,
    NotaryCommercialActivity,
    NotaryCrmAuditLog,
    NumberingSequence,
    Person,
    Role,
    RoleAssignment,
    TemplateField,
    TemplateRequiredRole,
    User,
)
from app.models.base import Base
