export type NotarialCatalogKey = string;

export type NotarialCatalogOption = {
  value: string;
  label: string;
};

export const EASYPRO1_NOTARIAL_CATALOGS: Record<string, NotarialCatalogOption[]> = {
  "TIPO DE DOCUMENTO": [
    { value: "C.C", label: "C.C" },
    { value: "C.E", label: "C.E" },
    { value: "PASAPORTE", label: "PASAPORTE" },
    { value: "PPT", label: "PPT" },
    { value: "R.C", label: "R.C" },
    { value: "T.I", label: "T.I" },
  ],
  "SEXO": [
    { value: "MASCULINO", label: "MASCULINO" },
    { value: "FEMENINO", label: "FEMENINO" },
    { value: "mujer", label: "mujer" },
  ],
  "NOTARIO": [
    { value: "ESTEBAN OCAMPO CARMONA", label: "ESTEBAN OCAMPO CARMONA" },
    { value: "JOSÉ MANUEL HERNÁNDEZ FRANCO", label: "JOSÉ MANUEL HERNÁNDEZ FRANCO" },
  ],
  "MES": [
    { value: "enero", label: "enero" },
    { value: "febrero", label: "febrero" },
    { value: "marzo", label: "marzo" },
    { value: "abril", label: "abril" },
    { value: "mayo", label: "mayo" },
    { value: "junio", label: "junio" },
    { value: "julio", label: "julio" },
    { value: "agosto", label: "agosto" },
    { value: "septiembre", label: "septiembre" },
    { value: "octubre", label: "octubre" },
    { value: "noviembre", label: "noviembre" },
    { value: "diciembre", label: "diciembre" },
  ],
  "NACIONALIDAD": [
    { value: "Venezolana", label: "Venezolana" },
    { value: "Española", label: "Española" },
    { value: "Ecuatoriana", label: "Ecuatoriana" },
    { value: "Argentina", label: "Argentina" },
    { value: "Peruana", label: "Peruana" },
    { value: "Colombiano", label: "Colombiano" },
    { value: "Colombiana", label: "Colombiana" },
    { value: "Peruano", label: "Peruano" },
    { value: "Argentino", label: "Argentino" },
    { value: "Ecuatoriano", label: "Ecuatoriano" },
    { value: "Estadounidense", label: "Estadounidense" },
    { value: "Español", label: "Español" },
    { value: "Chileno", label: "Chileno" },
    { value: "Chilena", label: "Chilena" },
    { value: "Panameño", label: "Panameño" },
    { value: "Panameña", label: "Panameña" },
    { value: "Paraguayo", label: "Paraguayo" },
    { value: "Paraguaya", label: "Paraguaya" },
    { value: "Portugués", label: "Portugués" },
    { value: "Portuguesa", label: "Portuguesa" },
    { value: "Polaco", label: "Polaco" },
    { value: "Polaca", label: "Polaca" },
    { value: "Ruso", label: "Ruso" },
    { value: "Rusa", label: "Rusa" },
    { value: "Venezolano", label: "Venezolano" },
    { value: "Mexicano", label: "Mexicano" },
    { value: "Mexicana", label: "Mexicana" },
    { value: "Guatemalteco", label: "Guatemalteco" },
    { value: "Guatemalteca", label: "Guatemalteca" },
    { value: "Griego", label: "Griego" },
    { value: "Griega", label: "Griega" },
    { value: "Francés", label: "Francés" },
    { value: "Francesa", label: "Francesa" },
    { value: "Salvadoreño", label: "Salvadoreño" },
    { value: "Salvadoreña", label: "Salvadoreña" },
    { value: "Egipcio", label: "Egipcio" },
    { value: "Egipcia", label: "Egipcia" },
    { value: "Emiratí", label: "Emiratí" },
    { value: "Alemán", label: "Alemán" },
    { value: "Alemana", label: "Alemana" },
    { value: "Saudí", label: "Saudí" },
    { value: "Boliviano", label: "Boliviano" },
    { value: "Boliviana", label: "Boliviana" },
    { value: "Brasileño", label: "Brasileño" },
    { value: "Brasileña", label: "Brasileña" },
    { value: "Chino", label: "Chino" },
    { value: "China", label: "China" },
    { value: "Costarricense", label: "Costarricense" },
    { value: "Croata", label: "Croata" },
    { value: "Cubano", label: "Cubano" },
    { value: "Cubana", label: "Cubana" },
  ],
  "GENERO": [
    { value: "mujer", label: "mujer" },
    { value: "varón", label: "varón" },
  ],
  "DÍAS": [
    { value: "primer (1er) día", label: "primer (1er) día" },
    { value: "dos (2) días", label: "dos (2) días" },
    { value: "tres (3) días", label: "tres (3) días" },
    { value: "cuatro (4) días", label: "cuatro (4) días" },
    { value: "cinco  (5) días", label: "cinco  (5) días" },
    { value: "seis (6) días", label: "seis (6) días" },
    { value: "siete (7) días", label: "siete (7) días" },
    { value: "ocho (8) días", label: "ocho (8) días" },
    { value: "nueve (9) días", label: "nueve (9) días" },
    { value: "diez (10) días", label: "diez (10) días" },
    { value: "once (11) días", label: "once (11) días" },
    { value: "doce (12) días", label: "doce (12) días" },
    { value: "trece (13) días", label: "trece (13) días" },
    { value: "catorce (14) días", label: "catorce (14) días" },
    { value: "quince (15) días", label: "quince (15) días" },
    { value: "dieciséis (16) días", label: "dieciséis (16) días" },
    { value: "diecisiete (17) días", label: "diecisiete (17) días" },
    { value: "dieciocho (18) días", label: "dieciocho (18) días" },
    { value: "diecinueve (19) días", label: "diecinueve (19) días" },
    { value: "veinte (20) días", label: "veinte (20) días" },
    { value: "ventiún (21) días", label: "ventiún (21) días" },
    { value: "veintidós (22) días", label: "veintidós (22) días" },
    { value: "veintitrés (23) días", label: "veintitrés (23) días" },
    { value: "veinticuatro (24) días", label: "veinticuatro (24) días" },
    { value: "veinticinco (25) días", label: "veinticinco (25) días" },
    { value: "veintiséis (26) días", label: "veintiséis (26) días" },
    { value: "veintisiete (27 )días", label: "veintisiete (27 )días" },
    { value: "veintiocho (28) días", label: "veintiocho (28) días" },
    { value: "veintinueve (29) días", label: "veintinueve (29) días" },
    { value: "treinta (30) días", label: "treinta (30) días" },
    { value: "treinta y un (31) días", label: "treinta y un (31) días" },
  ],
  "ESTADO CIVIL": [
    { value: "soltera sin unión marital de hecho", label: "soltera sin unión marital de hecho" },
    { value: "soltero sin unión marital de hecho", label: "soltero sin unión marital de hecho" },
    { value: "soltera con unión marital de hecho", label: "soltera con unión marital de hecho" },
    { value: "soltero con unión marital de hecho", label: "soltero con unión marital de hecho" },
    { value: "solteros con unión marital de hecho entre sí", label: "solteros con unión marital de hecho entre sí" },
    { value: "soltera por efecto de viudedad con sociedad conyugal disuelta y liquidada", label: "soltera por efecto de viudedad con sociedad conyugal disuelta y liquidada" },
    { value: "soltero por efecto de viudedad con sociedad conyugal disuelta y liquidada", label: "soltero por efecto de viudedad con sociedad conyugal disuelta y liquidada" },
    { value: "soltera por efecto de viudedad con sociedad conyugal disuelta e ilíquida", label: "soltera por efecto de viudedad con sociedad conyugal disuelta e ilíquida" },
    { value: "soltero por efecto de viudedad con sociedad conyugal disuelta e ilíquida", label: "soltero por efecto de viudedad con sociedad conyugal disuelta e ilíquida" },
    { value: "soltera con unión marital de hecho sin sociedad patrimonial por efecto de capitulaciones", label: "soltera con unión marital de hecho sin sociedad patrimonial por efecto de capitulaciones" },
    { value: "soltero con unión marital de hecho sin sociedad patrimonial por efecto de capitulaciones", label: "soltero con unión marital de hecho sin sociedad patrimonial por efecto de capitulaciones" },
    { value: "soltera por efecto de divorcio con sociedad conyugal disuelta y liquidada", label: "soltera por efecto de divorcio con sociedad conyugal disuelta y liquidada" },
    { value: "soltero por efecto de divorcio con sociedad conyugal disuelta y liquidada", label: "soltero por efecto de divorcio con sociedad conyugal disuelta y liquidada" },
    { value: "casada con sociedad conyugal vigente", label: "casada con sociedad conyugal vigente" },
    { value: "casado con sociedad conyugal vigente", label: "casado con sociedad conyugal vigente" },
    { value: "casada con sociedad conyugal disuelta y liquidada", label: "casada con sociedad conyugal disuelta y liquidada" },
    { value: "casado con sociedad conyugal disuelta y liquidada", label: "casado con sociedad conyugal disuelta y liquidada" },
    { value: "casados entre sí, con sociedad conyugal vigente", label: "casados entre sí, con sociedad conyugal vigente" },
    { value: "casada sin sociedad conyugal por efecto de capitulaciones", label: "casada sin sociedad conyugal por efecto de capitulaciones" },
    { value: "casado sin sociedad conyugal por efecto de capitulaciones", label: "casado sin sociedad conyugal por efecto de capitulaciones" },
    { value: "soltera con unión marital de hecho con sociedad patrimonial disuelta y liquidada", label: "soltera con unión marital de hecho con sociedad patrimonial disuelta y liquidada" },
    { value: "soltero con unión marital de hecho con sociedad patrimonial disuelta y liquidada", label: "soltero con unión marital de hecho con sociedad patrimonial disuelta y liquidada" },
    { value: "soltera por efectos de divorcio con sociedad conyugal disuelta e ilíquida", label: "soltera por efectos de divorcio con sociedad conyugal disuelta e ilíquida" },
  ],
  "MUNICIPIO": [
    { value: "Medellín, Antioquia", label: "Medellín, Antioquia" },
    { value: "Abejorral, Antioquia", label: "Abejorral, Antioquia" },
    { value: "Abriaquí", label: "Abriaquí" },
    { value: "Alejandría", label: "Alejandría" },
    { value: "Amagá, Antioquia", label: "Amagá, Antioquia" },
    { value: "Amalfi", label: "Amalfi" },
    { value: "Andes", label: "Andes" },
    { value: "Angelópolis, Antioquia", label: "Angelópolis, Antioquia" },
    { value: "Angostura", label: "Angostura" },
    { value: "Anori", label: "Anori" },
    { value: "Santa Fe De Antioquia", label: "Santa Fe De Antioquia" },
    { value: "Anza", label: "Anza" },
    { value: "Apartado", label: "Apartado" },
    { value: "Arboletes", label: "Arboletes" },
    { value: "Argelia", label: "Argelia" },
    { value: "Armenia", label: "Armenia" },
    { value: "Barbosa", label: "Barbosa" },
    { value: "Belmira", label: "Belmira" },
    { value: "Bello", label: "Bello" },
    { value: "Betania", label: "Betania" },
    { value: "Betulia", label: "Betulia" },
    { value: "Ciudad Bolivar", label: "Ciudad Bolivar" },
    { value: "Briceño", label: "Briceño" },
    { value: "Buritica", label: "Buritica" },
    { value: "Caceres", label: "Caceres" },
    { value: "Caicedo", label: "Caicedo" },
    { value: "Caldas, Antioquia", label: "Caldas, Antioquia" },
    { value: "Cañasgordas", label: "Cañasgordas" },
    { value: "Caracoli", label: "Caracoli" },
    { value: "Caramanta", label: "Caramanta" },
    { value: "Carepa", label: "Carepa" },
    { value: "Carmen De Viboral", label: "Carmen De Viboral" },
    { value: "Carolina Del Principe", label: "Carolina Del Principe" },
    { value: "Caucasia", label: "Caucasia" },
    { value: "Chigorodo", label: "Chigorodo" },
    { value: "Cisneros, Antioquia", label: "Cisneros, Antioquia" },
    { value: "Cocorna", label: "Cocorna" },
    { value: "Concepcion", label: "Concepcion" },
    { value: "Concordia", label: "Concordia" },
    { value: "Copacabana", label: "Copacabana" },
    { value: "Dabeiba", label: "Dabeiba" },
    { value: "Don Matias", label: "Don Matias" },
    { value: "Ebejico", label: "Ebejico" },
    { value: "El Bagre", label: "El Bagre" },
    { value: "Entrerrios", label: "Entrerrios" },
    { value: "Envigado", label: "Envigado" },
    { value: "Fredonia", label: "Fredonia" },
    { value: "Frontino", label: "Frontino" },
    { value: "Giraldo", label: "Giraldo" },
    { value: "Girardota", label: "Girardota" },
    { value: "Gomez Plata", label: "Gomez Plata" },
    { value: "Granada", label: "Granada" },
    { value: "Guadalupe", label: "Guadalupe" },
    { value: "Guarne", label: "Guarne" },
    { value: "Guatape", label: "Guatape" },
    { value: "Heliconia", label: "Heliconia" },
    { value: "Hispania", label: "Hispania" },
    { value: "Itagüi", label: "Itagüi" },
    { value: "Ituango", label: "Ituango" },
    { value: "Jardin", label: "Jardin" },
    { value: "Jerico", label: "Jerico" },
    { value: "La Ceja", label: "La Ceja" },
    { value: "La Estrella", label: "La Estrella" },
    { value: "La Pintada", label: "La Pintada" },
    { value: "La Union", label: "La Union" },
    { value: "Liborina", label: "Liborina" },
    { value: "Maceo", label: "Maceo" },
    { value: "Marinilla", label: "Marinilla" },
    { value: "Montebello", label: "Montebello" },
    { value: "Murindo", label: "Murindo" },
    { value: "Mutatá", label: "Mutatá" },
    { value: "Nariño", label: "Nariño" },
    { value: "Necocli", label: "Necocli" },
    { value: "Nechi", label: "Nechi" },
    { value: "Olaya", label: "Olaya" },
    { value: "Peñol", label: "Peñol" },
    { value: "Peque", label: "Peque" },
    { value: "Pueblorrico", label: "Pueblorrico" },
    { value: "Puerto Berrio", label: "Puerto Berrio" },
    { value: "Puerto Nare", label: "Puerto Nare" },
    { value: "Puerto Triunfo", label: "Puerto Triunfo" },
    { value: "Remedios", label: "Remedios" },
    { value: "Retiro", label: "Retiro" },
    { value: "Rionegro", label: "Rionegro" },
    { value: "Sabanalarga", label: "Sabanalarga" },
    { value: "Sabaneta", label: "Sabaneta" },
    { value: "Salgar", label: "Salgar" },
    { value: "San Andres", label: "San Andres" },
    { value: "San Carlos", label: "San Carlos" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "San Jeronimo", label: "San Jeronimo" },
    { value: "San Jose De La Montaña", label: "San Jose De La Montaña" },
    { value: "San Juan De Uraba", label: "San Juan De Uraba" },
    { value: "San Luis", label: "San Luis" },
    { value: "San Pedro", label: "San Pedro" },
    { value: "San Pedro De Uraba", label: "San Pedro De Uraba" },
    { value: "San Rafael", label: "San Rafael" },
    { value: "San Roque", label: "San Roque" },
    { value: "San Vicente", label: "San Vicente" },
    { value: "Santa Barbara", label: "Santa Barbara" },
    { value: "Santa Rosa de Osos", label: "Santa Rosa de Osos" },
    { value: "Santo Domingo", label: "Santo Domingo" },
    { value: "Santuario", label: "Santuario" },
    { value: "Segovia", label: "Segovia" },
    { value: "Sonsón", label: "Sonsón" },
    { value: "Sopetrán", label: "Sopetrán" },
    { value: "Támesis", label: "Támesis" },
    { value: "Tarazá", label: "Tarazá" },
    { value: "Tarso", label: "Tarso" },
    { value: "Titiribi", label: "Titiribi" },
    { value: "Toledo", label: "Toledo" },
    { value: "Turbo", label: "Turbo" },
    { value: "Uramita", label: "Uramita" },
    { value: "Urrao", label: "Urrao" },
    { value: "Valdivia", label: "Valdivia" },
    { value: "Valparaiso", label: "Valparaiso" },
    { value: "Vegachí", label: "Vegachí" },
    { value: "Venecia", label: "Venecia" },
    { value: "Vigía del Fuerte", label: "Vigía del Fuerte" },
    { value: "Yalí", label: "Yalí" },
    { value: "Yarumal", label: "Yarumal" },
    { value: "Yolombo", label: "Yolombo" },
    { value: "Yondo", label: "Yondo" },
    { value: "Zaragoza", label: "Zaragoza" },
    { value: "Bogotá", label: "Bogotá" },
    { value: "Tunja", label: "Tunja" },
    { value: "este municipio", label: "este municipio" },
    { value: "Montelíbano", label: "Montelíbano" },
    { value: "San Marcos", label: "San Marcos" },
  ],
  "ACTOS": [
    { value: "ACCESIÓN DEL SUELO", label: "ACCESIÓN DEL SUELO" },
    { value: "ACTA ENTREGA DE INMUEBLES A ENTIDAD", label: "ACTA ENTREGA DE INMUEBLES A ENTIDAD" },
    { value: "ADJUDICACIÓN BALDÍOS", label: "ADJUDICACIÓN BALDÍOS" },
    { value: "ADJUDICACIÓN BALDÍOS EN PROPIEDAD COLECTIVA A COMUNIDADES NEGRAS", label: "ADJUDICACIÓN BALDÍOS EN PROPIEDAD COLECTIVA A COMUNIDADES NEGRAS" },
    { value: "ADJUDICACIÓN BALDÍOS RESGUARDOS INDÍGENAS", label: "ADJUDICACIÓN BALDÍOS RESGUARDOS INDÍGENAS" },
    { value: "ADJUDICACIÓN DE BIENES VACANTES", label: "ADJUDICACIÓN DE BIENES VACANTES" },
    { value: "ADJUDICACIÓN DE LA COSA HIPOTECADA", label: "ADJUDICACIÓN DE LA COSA HIPOTECADA" },
    { value: "ADJUDICACIÓN EN REMATE", label: "ADJUDICACIÓN EN REMATE" },
    { value: "ADJUDICACIÓN EN SUCESIÓN", label: "ADJUDICACIÓN EN SUCESIÓN" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN DE LA COMUNIDAD", label: "ADJUDICACIÓN LIQUIDACIÓN DE LA COMUNIDAD" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD COMERCIAL", label: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD COMERCIAL" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD  CONYUGAL", label: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD  CONYUGAL" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD PATRIMONIAL DE HECHO", label: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD PATRIMONIAL DE HECHO" },
    { value: "ADJUDICACIÓN POR EXPROPIACIÓN", label: "ADJUDICACIÓN POR EXPROPIACIÓN" },
    { value: "ADJUDICACIÓN SUCESIÓN PARTICIÓN ADICIONAL", label: "ADJUDICACIÓN SUCESIÓN PARTICIÓN ADICIONAL" },
    { value: "ADJUDICACIÓN UNIDAD AGRÍCOLA FAMILIAR  --UAF--", label: "ADJUDICACIÓN UNIDAD AGRÍCOLA FAMILIAR  --UAF--" },
    { value: "ADQUISICIÓN POR ABSORCIÓN DE ACCIONES Y PATRIMONIO DE ENTIDADES FINANCIERAS", label: "ADQUISICIÓN POR ABSORCIÓN DE ACCIONES Y PATRIMONIO DE ENTIDADES FINANCIERAS" },
    { value: "APORTE A SOCIEDAD", label: "APORTE A SOCIEDAD" },
    { value: "APORTE DE SUBSIDIO EN ESPECIE", label: "APORTE DE SUBSIDIO EN ESPECIE" },
    { value: "CADUCIDAD ADMINISTRATIVA", label: "CADUCIDAD ADMINISTRATIVA" },
    { value: "CESIÓN A TITULO GRATUITO DE BIENES FISCALES", label: "CESIÓN A TITULO GRATUITO DE BIENES FISCALES" },
    { value: "CESIÓN DE BIENES OBLIGATORIA", label: "CESIÓN DE BIENES OBLIGATORIA" },
    { value: "CESIÓN DE CONTRATO", label: "CESIÓN DE CONTRATO" },
    { value: "CESIÓN OBLIGATORIA DE ZONAS CON DESTINO A USO PUBLICO", label: "CESIÓN OBLIGATORIA DE ZONAS CON DESTINO A USO PUBLICO" },
    { value: "COMPRAVENTA", label: "COMPRAVENTA" },
    { value: "COMPRAVENTA PARCIAL", label: "COMPRAVENTA PARCIAL" },
    { value: "CONSOLIDACIÓN DE DOMINIO PLENO", label: "CONSOLIDACIÓN DE DOMINIO PLENO" },
    { value: "CONSTITUCIÓN DE FIDUCIA MERCANTIL", label: "CONSTITUCIÓN DE FIDUCIA MERCANTIL" },
    { value: "DACIÓN EN PAGO", label: "DACIÓN EN PAGO" },
    { value: "DACIÓN EN PAGO OBLIGATORIA", label: "DACIÓN EN PAGO OBLIGATORIA" },
    { value: "DECLARACIÓN JUDICIAL DE PERTENENCIA", label: "DECLARACIÓN JUDICIAL DE PERTENENCIA" },
    { value: "DECLARATORIA DE NULIDAD DE ESCRITURA PUBLICA", label: "DECLARATORIA DE NULIDAD DE ESCRITURA PUBLICA" },
    { value: "DECLARATORIA DE PROPIEDAD PUBLICA SOBRE ZONAS DE CESIÓN OBLIGATORIA GRATUITA", label: "DECLARATORIA DE PROPIEDAD PUBLICA SOBRE ZONAS DE CESIÓN OBLIGATORIA GRATUITA" },
    { value: "DECLARATORIA RECUPERACIÓN TITULARIDAD DE BIEN EXPROPIADO", label: "DECLARATORIA RECUPERACIÓN TITULARIDAD DE BIEN EXPROPIADO" },
    { value: "DECLARATORIA SIMULACIÓN DE CONTRATO", label: "DECLARATORIA SIMULACIÓN DE CONTRATO" },
    { value: "DECRETO DE POSESIÓN EFECTIVA", label: "DECRETO DE POSESIÓN EFECTIVA" },
    { value: "DESTINACIÓN DEFINITIVA", label: "DESTINACIÓN DEFINITIVA" },
    { value: "DONACIÓN", label: "DONACIÓN" },
    { value: "ESCISIÓN", label: "ESCISIÓN" },
    { value: "EXPROPIACIÓN POR VÍA ADMINISTRATIVA", label: "EXPROPIACIÓN POR VÍA ADMINISTRATIVA" },
    { value: "EXPROPIACIÓN POR VÍA JUDICIAL", label: "EXPROPIACIÓN POR VÍA JUDICIAL" },
    { value: "EXTINCIÓN DEL DERECHO DE DOMINIO PRIVADO", label: "EXTINCIÓN DEL DERECHO DE DOMINIO PRIVADO" },
    { value: "FUSIÓN", label: "FUSIÓN" },
    { value: "PERMUTA", label: "PERMUTA" },
    { value: "PRESCRIPCIÓN AGRARIA", label: "PRESCRIPCIÓN AGRARIA" },
    { value: "RATIFICACIÓN CONTRATO", label: "RATIFICACIÓN CONTRATO" },
    { value: "RECUPERACIÓN PARCIAL TITULARIDAD BIEN EXPROPIADO", label: "RECUPERACIÓN PARCIAL TITULARIDAD BIEN EXPROPIADO" },
    { value: "RECUPERACIÓN TOTAL TITULARIDAD BIEN EXPROPIADO", label: "RECUPERACIÓN TOTAL TITULARIDAD BIEN EXPROPIADO" },
    { value: "REIVINDICACIÓN", label: "REIVINDICACIÓN" },
    { value: "RENTA VITALICIA", label: "RENTA VITALICIA" },
    { value: "RESCILIACIN2", label: "RESCILIACIN2" },
    { value: "RESCILIACIÓN", label: "RESCILIACIÓN" },
    { value: "RESOLUCIÓN CONTRATO", label: "RESOLUCIÓN CONTRATO" },
    { value: "RESTITUCIÓN FIDEICOMISO CIVIL", label: "RESTITUCIÓN FIDEICOMISO CIVIL" },
    { value: "RESTITUCIÓN EN FIDUCIA MERCANTIL", label: "RESTITUCIÓN EN FIDUCIA MERCANTIL" },
    { value: "REVERSIÓN DEL BALDÍO", label: "REVERSIÓN DEL BALDÍO" },
    { value: "REVOCACIÓN ADJUDICACIÓN BALDÍOS EN PROPIEDAD COLECTIVA A COMUNIDADES NEGRAS", label: "REVOCACIÓN ADJUDICACIÓN BALDÍOS EN PROPIEDAD COLECTIVA A COMUNIDADES NEGRAS" },
    { value: "REVOCATORIA ADMINISTRATIVA", label: "REVOCATORIA ADMINISTRATIVA" },
    { value: "REVOCATORIA CONCURSAL", label: "REVOCATORIA CONCURSAL" },
    { value: "REVOCATORIA VOLUNTARIA", label: "REVOCATORIA VOLUNTARIA" },
    { value: "TITULO DE MINAS CON ANTECEDENTE REGISTRAL", label: "TITULO DE MINAS CON ANTECEDENTE REGISTRAL" },
    { value: "TRANSACCIÓN", label: "TRANSACCIÓN" },
    { value: "TRANSFERENCIA DE DOMINIO A TITULO DE BENEFICIO EN FIDUCIA  MERCANTIL", label: "TRANSFERENCIA DE DOMINIO A TITULO DE BENEFICIO EN FIDUCIA  MERCANTIL" },
    { value: "TRANSFERENCIA DE DOMINO POR SOLUCIÓN O PAGO EFECTIVO", label: "TRANSFERENCIA DE DOMINO POR SOLUCIÓN O PAGO EFECTIVO" },
    { value: "TRANSFERENCIA DE DOMINIO A TITULO DE LEASING HABITACIONAL DE VIVIENDA FAMILIAR.", label: "TRANSFERENCIA DE DOMINIO A TITULO DE LEASING HABITACIONAL DE VIVIENDA FAMILIAR." },
    { value: "TRANSFERENCIA DE DOMINIO A TITULO DE LEASING HABITACIONAL DE VIVIENDA NO FAMILIAR", label: "TRANSFERENCIA DE DOMINIO A TITULO DE LEASING HABITACIONAL DE VIVIENDA NO FAMILIAR" },
    { value: "TITULACIÓN POR SANEAMIENTO CONTABLE", label: "TITULACIÓN POR SANEAMIENTO CONTABLE" },
    { value: "ENTREGA ANTICIPADA DE CESIONES", label: "ENTREGA ANTICIPADA DE CESIONES" },
    { value: "SANEAMIENTO TITULACIÓN LEY 1182 DE 2008", label: "SANEAMIENTO TITULACIÓN LEY 1182 DE 2008" },
    { value: "DECLARATORIA DE PRESCRIPCIÓN ADQUISITIVA DE DOMINIO VIS ART. 10 LEY 1183 DE 2008", label: "DECLARATORIA DE PRESCRIPCIÓN ADQUISITIVA DE DOMINIO VIS ART. 10 LEY 1183 DE 2008" },
    { value: "AMPLIACIÓN DE HIPOTECA", label: "AMPLIACIÓN DE HIPOTECA" },
    { value: "CONSTITUCIÓN DE MOVILIZACIÓN", label: "CONSTITUCIÓN DE MOVILIZACIÓN" },
    { value: "HIPOTECA", label: "HIPOTECA" },
    { value: "HIPOTECA ABIERTA", label: "HIPOTECA ABIERTA" },
    { value: "HIPOTECA CON CUANTÍA INDETERMINADA", label: "HIPOTECA CON CUANTÍA INDETERMINADA" },
    { value: "HIPOTECA DE BIENES EN USUFRUCTO", label: "HIPOTECA DE BIENES EN USUFRUCTO" },
    { value: "HIPOTECA DE  DERECHOS  Y ACCIONES", label: "HIPOTECA DE  DERECHOS  Y ACCIONES" },
    { value: "HIPOTECA DE GANANCIALES", label: "HIPOTECA DE GANANCIALES" },
    { value: "HIPOTECA DE MINAS CON ANTECEDENTE REGISTRAL", label: "HIPOTECA DE MINAS CON ANTECEDENTE REGISTRAL" },
    { value: "HIPOTECA DE UNIDAD AGRÍCOLA FAMILIAR", label: "HIPOTECA DE UNIDAD AGRÍCOLA FAMILIAR" },
    { value: "HIPOTECA DE DERECHOS DE CUOTA", label: "HIPOTECA DE DERECHOS DE CUOTA" },
    { value: "VALORIZACIÓN", label: "VALORIZACIÓN" },
    { value: "HIPOTECA NUDA PROPIEDAD", label: "HIPOTECA NUDA PROPIEDAD" },
    { value: "LIQUIDACIÓN DEL EFECTO PLUSVALÍA", label: "LIQUIDACIÓN DEL EFECTO PLUSVALÍA" },
    { value: "ADJUDICACIÓN SUCESIÓN DERECHOS DE CUOTA", label: "ADJUDICACIÓN SUCESIÓN DERECHOS DE CUOTA" },
    { value: "ADJUDICACIÓN SUCESIÓN NUDA PROPIEDAD", label: "ADJUDICACIÓN SUCESIÓN NUDA PROPIEDAD" },
    { value: "ADJUDICACIÓN SUCESIÓN SUBSUELO CON ANTECEDENTE REGISTRAL", label: "ADJUDICACIÓN SUCESIÓN SUBSUELO CON ANTECEDENTE REGISTRAL" },
    { value: "AFECTACIÓN A VIVIENDA FAMILIAR", label: "AFECTACIÓN A VIVIENDA FAMILIAR" },
    { value: "AFECTACIÓN POR CAUSA DE UNA OBRA PUBLICA", label: "AFECTACIÓN POR CAUSA DE UNA OBRA PUBLICA" },
    { value: "CAMBIO RÉGIMEN DE COPROPIEDAD", label: "CAMBIO RÉGIMEN DE COPROPIEDAD" },
    { value: "COMPRAVENTA DERECHOS DE CUOTA", label: "COMPRAVENTA DERECHOS DE CUOTA" },
    { value: "COMPRAVENTA  NUDA PROPIEDAD", label: "COMPRAVENTA  NUDA PROPIEDAD" },
    { value: "COMPRAVENTA SUBSUELO CON ANTECEDENTE REGISTRAL", label: "COMPRAVENTA SUBSUELO CON ANTECEDENTE REGISTRAL" },
    { value: "COMPRAVENTA USUFRUCTO", label: "COMPRAVENTA USUFRUCTO" },
    { value: "CONDICIÓN RESOLUTORIA EXPRESA", label: "CONDICIÓN RESOLUTORIA EXPRESA" },
    { value: "CONDICIÓN SUSPENSIVA", label: "CONDICIÓN SUSPENSIVA" },
    { value: "CONSTITUCIÓN DE FIDEICOMISO CIVIL", label: "CONSTITUCIÓN DE FIDEICOMISO CIVIL" },
    { value: "CONSTITUCIÓN DE USUFRUCTO", label: "CONSTITUCIÓN DE USUFRUCTO" },
    { value: "CONSTITUCIÓN PATRIMONIO DE FAMILIA", label: "CONSTITUCIÓN PATRIMONIO DE FAMILIA" },
    { value: "CONSTITUCIÓN RÉGIMEN DE CONDOMINIO", label: "CONSTITUCIÓN RÉGIMEN DE CONDOMINIO" },
    { value: "CONSTITUCIÓN REGLAMENTO DE PROPIEDAD HORIZONTAL", label: "CONSTITUCIÓN REGLAMENTO DE PROPIEDAD HORIZONTAL" },
    { value: "DECLARATORIA DE INDIVISIÓN", label: "DECLARATORIA DE INDIVISIÓN" },
    { value: "DERECHO DE HABITACIÓN", label: "DERECHO DE HABITACIÓN" },
    { value: "DERECHO DE USO", label: "DERECHO DE USO" },
    { value: "DESLINDE Y AMOJONAMIENTO", label: "DESLINDE Y AMOJONAMIENTO" },
    { value: "DONACIÓN NUDA PROPIEDAD", label: "DONACIÓN NUDA PROPIEDAD" },
    { value: "DONACIÓN DE USUFRUCTO", label: "DONACIÓN DE USUFRUCTO" },
    { value: "LIQUIDACIÓN DEL EFECTO DE PLUSVALÍA", label: "LIQUIDACIÓN DEL EFECTO DE PLUSVALÍA" },
    { value: "MEDIANERÍA", label: "MEDIANERÍA" },
    { value: "PACTO COMISORIO", label: "PACTO COMISORIO" },
    { value: "PACTO DE INDIVISIÓN", label: "PACTO DE INDIVISIÓN" },
    { value: "PACTO DE RESERVA DE DOMINIO", label: "PACTO DE RESERVA DE DOMINIO" },
    { value: "PACTO DE RETROVENTA", label: "PACTO DE RETROVENTA" },
    { value: "REFORMA RÉGIMEN DE CONDOMINIO", label: "REFORMA RÉGIMEN DE CONDOMINIO" },
    { value: "REFORMA REGLAMENTO DE PROPIEDAD HORIZONTAL", label: "REFORMA REGLAMENTO DE PROPIEDAD HORIZONTAL" },
    { value: "REMATE DERECHO DE CUOTA", label: "REMATE DERECHO DE CUOTA" },
    { value: "RESERVA DERECHO DE USUFRUCTO", label: "RESERVA DERECHO DE USUFRUCTO" },
    { value: "SERVIDUMBRE DE ACUEDUCTO ACTIVA", label: "SERVIDUMBRE DE ACUEDUCTO ACTIVA" },
    { value: "SERVIDUMBRE DE ACUEDUCTO PASIVA", label: "SERVIDUMBRE DE ACUEDUCTO PASIVA" },
    { value: "SERVIDUMBRE DE AGUAS NEGRAS ACTIVA", label: "SERVIDUMBRE DE AGUAS NEGRAS ACTIVA" },
    { value: "SERVIDUMBRE DE AGUAS NEGRAS PASIVA", label: "SERVIDUMBRE DE AGUAS NEGRAS PASIVA" },
    { value: "SERVIDUMBRE DE AIRE", label: "SERVIDUMBRE DE AIRE" },
    { value: "SERVIDUMBRE DE ENERGÍA  ELÉCTRICA", label: "SERVIDUMBRE DE ENERGÍA  ELÉCTRICA" },
    { value: "SERVIDUMBRE DE GASODUCTO", label: "SERVIDUMBRE DE GASODUCTO" },
    { value: "SERVIDUMBRE DE LUZ", label: "SERVIDUMBRE DE LUZ" },
    { value: "SERVIDUMBRE DE OLEODUCTO", label: "SERVIDUMBRE DE OLEODUCTO" },
    { value: "SERVIDUMBRE DE TRANSITO ACTIVA", label: "SERVIDUMBRE DE TRANSITO ACTIVA" },
    { value: "SERVIDUMBRE DE TRANSITO PASIVA", label: "SERVIDUMBRE DE TRANSITO PASIVA" },
    { value: "AFECTACIÓN  POR CAUSA DE CATEGORÍAS AMBIENTALES (SERVIDUMBRE ECOLÓGICA)", label: "AFECTACIÓN  POR CAUSA DE CATEGORÍAS AMBIENTALES (SERVIDUMBRE ECOLÓGICA)" },
    { value: "ADICIÓN RÉGIMEN DE CONDOMINIO", label: "ADICIÓN RÉGIMEN DE CONDOMINIO" },
    { value: "ADICIÓN RÉGIMEN DE PROPIEDAD HORIZONTAL", label: "ADICIÓN RÉGIMEN DE PROPIEDAD HORIZONTAL" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN DE LA SOCIEDAD CONYUGAL DERECHO DE CUOTA", label: "ADJUDICACIÓN LIQUIDACIÓN DE LA SOCIEDAD CONYUGAL DERECHO DE CUOTA" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN  DE LA SOCIEDAD CONYUGAL NUDA PROPIEDAD", label: "ADJUDICACIÓN LIQUIDACIÓN  DE LA SOCIEDAD CONYUGAL NUDA PROPIEDAD" },
    { value: "SERVIDUMBRE DE AGUA ACTIVA", label: "SERVIDUMBRE DE AGUA ACTIVA" },
    { value: "SERVIDUMBRE DE AGUA PASIVA", label: "SERVIDUMBRE DE AGUA PASIVA" },
    { value: "DECLARATORIA DE ZONAS DE INMINENCIA DE RIESGO DE DESPLAZAMIENTO Y DE DESPLAZAMIENTO FORZADO", label: "DECLARATORIA DE ZONAS DE INMINENCIA DE RIESGO DE DESPLAZAMIENTO Y DE DESPLAZAMIENTO FORZADO" },
    { value: "DECLARATORIA  DE ZONA DE DESPLAZAMIENTO FORZADO", label: "DECLARATORIA  DE ZONA DE DESPLAZAMIENTO FORZADO" },
    { value: "SERVIDUMBRE MINERA", label: "SERVIDUMBRE MINERA" },
    { value: "MEDIDA CAUTELAR", label: "MEDIDA CAUTELAR" },
    { value: "COMISO ESPECIAL", label: "COMISO ESPECIAL" },
    { value: "DECLARACIÓN NO PODRÁ REMATARSE, ADJUDICARSE, NI ENAJENARSE A NINGÚN TITULO BIENES DEL GARANTE", label: "DECLARACIÓN NO PODRÁ REMATARSE, ADJUDICARSE, NI ENAJENARSE A NINGÚN TITULO BIENES DEL GARANTE" },
    { value: "DECLARATORIA DE INTERÉS", label: "DECLARATORIA DE INTERÉS" },
    { value: "DECLARATORIA DE UTILIDAD PUBLICA", label: "DECLARATORIA DE UTILIDAD PUBLICA" },
    { value: "DECOMISO DE BIENES", label: "DECOMISO DE BIENES" },
    { value: "DEMANDA EN ACCIÓN DE SIMULACIÓN", label: "DEMANDA EN ACCIÓN DE SIMULACIÓN" },
    { value: "DEMANDA EN ACCIÓN REVOCATORIA", label: "DEMANDA EN ACCIÓN REVOCATORIA" },
    { value: "DEMANDA EN ACUERDO DE REESTRUCTURACIÓN", label: "DEMANDA EN ACUERDO DE REESTRUCTURACIÓN" },
    { value: "DEMANDA EN PROCESO  DE DECLARATORIA DE UNIÓN MARITAL DE HECHO", label: "DEMANDA EN PROCESO  DE DECLARATORIA DE UNIÓN MARITAL DE HECHO" },
    { value: "DEMANDA EN PROCESO DE DESLINDE Y AMOJONAMIENTO", label: "DEMANDA EN PROCESO DE DESLINDE Y AMOJONAMIENTO" },
    { value: "DEMANDA EN PROCESO DE DIVORCIO", label: "DEMANDA EN PROCESO DE DIVORCIO" },
    { value: "DEMANDA EN PROCESO DE PERTENENCIA", label: "DEMANDA EN PROCESO DE PERTENENCIA" },
    { value: "DEMANDA EN PROCESO DE SEPARACIÓN DE CUERPOS", label: "DEMANDA EN PROCESO DE SEPARACIÓN DE CUERPOS" },
    { value: "DEMANDA EN PROCESO DE SERVIDUMBRES", label: "DEMANDA EN PROCESO DE SERVIDUMBRES" },
    { value: "DEMANDA EN PROCESO DIVISORIO", label: "DEMANDA EN PROCESO DIVISORIO" },
    { value: "DEMANDA EN PROCESO DE SEPARACIÓN DE BIENES", label: "DEMANDA EN PROCESO DE SEPARACIÓN DE BIENES" },
    { value: "DEMANDA ORDINARIA DE ENRIQUECIMIENTO SIN JUSTA CAUSA", label: "DEMANDA ORDINARIA DE ENRIQUECIMIENTO SIN JUSTA CAUSA" },
    { value: "DEMANDA ORDINARIA POR LESIÓN ENORME", label: "DEMANDA ORDINARIA POR LESIÓN ENORME" },
    { value: "DEMANDA POR EXPROPIACIÓN", label: "DEMANDA POR EXPROPIACIÓN" },
    { value: "DEMANDA POR INEFICACIA  DEL ACUERDO DE REESTRUCTURACIÓN", label: "DEMANDA POR INEFICACIA  DEL ACUERDO DE REESTRUCTURACIÓN" },
    { value: "DERECHO DE PREFERENCIA", label: "DERECHO DE PREFERENCIA" },
    { value: "EMBARGO CONCORDATARIO", label: "EMBARGO CONCORDATARIO" },
    { value: "EMBARGO DE ALIMENTOS", label: "EMBARGO DE ALIMENTOS" },
    { value: "EMBARGO DE BIENES Y HABERES DE PROPIEDAD DEL INTERVENIDO", label: "EMBARGO DE BIENES Y HABERES DE PROPIEDAD DEL INTERVENIDO" },
    { value: "EMBARGO DE LA SUCESIÓN", label: "EMBARGO DE LA SUCESIÓN" },
    { value: "EMBARGO DE DERECHOS Y ACCIONES POR GARANTÍA HIPOTECARIA", label: "EMBARGO DE DERECHOS Y ACCIONES POR GARANTÍA HIPOTECARIA" },
    { value: "EMBARGO EJECUTIVO CON ACCIÓN PERSONAL", label: "EMBARGO EJECUTIVO CON ACCIÓN PERSONAL" },
    { value: "EMBARGO EJECUTIVO CON ACCIÓN MIXTA", label: "EMBARGO EJECUTIVO CON ACCIÓN MIXTA" },
    { value: "EMBARGO EJECUTIVO CON ACCIÓN REAL", label: "EMBARGO EJECUTIVO CON ACCIÓN REAL" },
    { value: "EMBARGO EJECUTIVO DERECHOS DE CUOTA", label: "EMBARGO EJECUTIVO DERECHOS DE CUOTA" },
    { value: "EMBARGO EN ACCIÓN DE SIMULACIÓN", label: "EMBARGO EN ACCIÓN DE SIMULACIÓN" },
    { value: "EMBARGO EN ACCIÓN REVOCATORIA", label: "EMBARGO EN ACCIÓN REVOCATORIA" },
    { value: "EMBARGO EN ACUERDO DE REESTRUCTURACIÓN", label: "EMBARGO EN ACUERDO DE REESTRUCTURACIÓN" },
    { value: "EMBARGO EN LIQUIDACIÓN OBLIGATORIA", label: "EMBARGO EN LIQUIDACIÓN OBLIGATORIA" },
    { value: "EMBARGO EN PROCESO DE DIVORCIO", label: "EMBARGO EN PROCESO DE DIVORCIO" },
    { value: "EMBARGO EN PROCESO DE FISCALÍA", label: "EMBARGO EN PROCESO DE FISCALÍA" },
    { value: "EMBARGO EN PROCESO DE SEPARACIÓN DE BIENES", label: "EMBARGO EN PROCESO DE SEPARACIÓN DE BIENES" },
    { value: "EMBARGO ESPECIAL ART. 341 CÓDIGO DE PROCEDIMIENTO PENAL", label: "EMBARGO ESPECIAL ART. 341 CÓDIGO DE PROCEDIMIENTO PENAL" },
    { value: "EMBARGO LABORAL", label: "EMBARGO LABORAL" },
    { value: "EMBARGO PENAL", label: "EMBARGO PENAL" },
    { value: "EMBARGO POR IMPUESTOS MUNICIPALES", label: "EMBARGO POR IMPUESTOS MUNICIPALES" },
    { value: "EMBARGO POR IMPUESTOS", label: "EMBARGO POR IMPUESTOS" },
    { value: "EMBARGO POR INEFICACIA DEL ACUERDO DE REESTRUCTURACIÓN", label: "EMBARGO POR INEFICACIA DEL ACUERDO DE REESTRUCTURACIÓN" },
    { value: "EMBARGO POR JURISDICCIÓN COACTIVA", label: "EMBARGO POR JURISDICCIÓN COACTIVA" },
    { value: "EMBARGO POR VALORIZACIÓN", label: "EMBARGO POR VALORIZACIÓN" },
    { value: "INICIACIÓN DEL PROCESO DE ENAJENACIÓN FORZOSA", label: "INICIACIÓN DEL PROCESO DE ENAJENACIÓN FORZOSA" },
    { value: "INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DE CLARIFICACIÓN DE LA PROPIEDAD", label: "INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DE CLARIFICACIÓN DE LA PROPIEDAD" },
    { value: "INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DESLINDE TIERRAS DE PROPIEDAD DE LA NACIÓN", label: "INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DESLINDE TIERRAS DE PROPIEDAD DE LA NACIÓN" },
    { value: "INICIACIÓN  DILIGENCIAS ADMINISTRATIVAS POR INDEBIDA OCUPACIÓN DE BALDÍOS", label: "INICIACIÓN  DILIGENCIAS ADMINISTRATIVAS POR INDEBIDA OCUPACIÓN DE BALDÍOS" },
    { value: "INICIACIÓN PROCEDIMIENTO DE EXPROPIACIÓN POR VÍA ADMINISTRATIVA", label: "INICIACIÓN PROCEDIMIENTO DE EXPROPIACIÓN POR VÍA ADMINISTRATIVA" },
    { value: "INICIACIÓN PROCEDIMIENTO DE EXTINCIÓN DEL DERECHO DE DOMINIO", label: "INICIACIÓN PROCEDIMIENTO DE EXTINCIÓN DEL DERECHO DE DOMINIO" },
    { value: "INICIACIÓN PROCESO ADMINISTRATIVO DE ADQUISICIÓN", label: "INICIACIÓN PROCESO ADMINISTRATIVO DE ADQUISICIÓN" },
    { value: "INSCRIPCIÓN DEL PROCESO ARBITRAL", label: "INSCRIPCIÓN DEL PROCESO ARBITRAL" },
    { value: "OFERTA DE COMPRA EN BIEN RURAL", label: "OFERTA DE COMPRA EN BIEN RURAL" },
    { value: "OFERTA DE COMPRA EN BIEN URBANO", label: "OFERTA DE COMPRA EN BIEN URBANO" },
    { value: "PREVENCIÓN NO PROCEDE LA REALIZACIÓN DE NUEVOS EMBARGOS SOBRE BIENES DE LA INTERVENIDA", label: "PREVENCIÓN NO PROCEDE LA REALIZACIÓN DE NUEVOS EMBARGOS SOBRE BIENES DE LA INTERVENIDA" },
    { value: "PREVENCIÓN REGISTRADORES ABSTENERSE CANCELAR GRAVÁMENES SALVO AUTORIZACIÓN AGENTE ESPECIAL", label: "PREVENCIÓN REGISTRADORES ABSTENERSE CANCELAR GRAVÁMENES SALVO AUTORIZACIÓN AGENTE ESPECIAL" },
    { value: "PROHIBICIÓN ADMINISTRATIVA", label: "PROHIBICIÓN ADMINISTRATIVA" },
    { value: "PROHIBICIÓN CANCELACIÓN GRAVÁMENES CONSTITUIDOS A FAVOR DE INTERVENIDA SIN AUTORIZACIÓN LIQUIDADOR", label: "PROHIBICIÓN CANCELACIÓN GRAVÁMENES CONSTITUIDOS A FAVOR DE INTERVENIDA SIN AUTORIZACIÓN LIQUIDADOR" },
    { value: "PROHIBICIÓN DE ENAJENAR SIN AUTORIZACIÓN", label: "PROHIBICIÓN DE ENAJENAR SIN AUTORIZACIÓN" },
    { value: "PROHIBICIÓN GRAVAR, CEDER, LIMITAR O ARRENDAR SIN AUTORIZACIÓN", label: "PROHIBICIÓN GRAVAR, CEDER, LIMITAR O ARRENDAR SIN AUTORIZACIÓN" },
    { value: "PROHIBICIÓN INSCRIPCIÓN ACTOS AFECTEN DOMINIO DE BIENES INTERVENIDA SALVO LO REALIZADO POR AGENTE ESPECIAL", label: "PROHIBICIÓN INSCRIPCIÓN ACTOS AFECTEN DOMINIO DE BIENES INTERVENIDA SALVO LO REALIZADO POR AGENTE ESPECIAL" },
    { value: "PROHIBICIÓN JUDICIAL", label: "PROHIBICIÓN JUDICIAL" },
    { value: "PROHIBICIÓN REGISTRO ACTOS AFECTEN DOMINIO BIENES PROPIEDAD DE INTERVENIDA SALVO AUTORIZACIÓN LIQUIDADOR", label: "PROHIBICIÓN REGISTRO ACTOS AFECTEN DOMINIO BIENES PROPIEDAD DE INTERVENIDA SALVO AUTORIZACIÓN LIQUIDADOR" },
    { value: "SUSPENSIÓN EXIGIBILIDAD DE GRAVÁMENES Y GARANTÍAS REALES Y FIDUCIARIAS", label: "SUSPENSIÓN EXIGIBILIDAD DE GRAVÁMENES Y GARANTÍAS REALES Y FIDUCIARIAS" },
    { value: "TOMA DE POSESIÓN INMEDIATA DE BIENES, HABERES Y NEGOCIOS DE ENTIDAD VIGILADA", label: "TOMA DE POSESIÓN INMEDIATA DE BIENES, HABERES Y NEGOCIOS DE ENTIDAD VIGILADA" },
    { value: "DEMANDA EN ACCIÓN DE PETICIÓN DE HERENCIA", label: "DEMANDA EN ACCIÓN DE PETICIÓN DE HERENCIA" },
    { value: "DEMANDA EN PROCESO ORDINARIO", label: "DEMANDA EN PROCESO ORDINARIO" },
    { value: "DEMANDA EN PROCESO REIVINDICATORIO", label: "DEMANDA EN PROCESO REIVINDICATORIO" },
    { value: "PREVENCIÓN REGISTRADORES ABSTENERSE DE INSCRIBIR ACTOS DE ENAJENACIÓN O TRANSFERENCIA A CUALQUIER TÍTULO DE BIENES RURALES. DECRETO 2007 DE 2001.", label: "PREVENCIÓN REGISTRADORES ABSTENERSE DE INSCRIBIR ACTOS DE ENAJENACIÓN O TRANSFERENCIA A CUALQUIER TÍTULO DE BIENES RURALES. DECRETO 2007 DE 2001." },
    { value: "EMBARGO EN PROCESO DE JURISDICCIÓN VOLUNTARIA", label: "EMBARGO EN PROCESO DE JURISDICCIÓN VOLUNTARIA" },
    { value: "EMBARGO EN PROCESO ORDINARIO", label: "EMBARGO EN PROCESO ORDINARIO" },
    { value: "DEMANDA EN PROCESO LIQUIDATORIO", label: "DEMANDA EN PROCESO LIQUIDATORIO" },
    { value: "PROHIBICIÓN DE ENAJENAR O TRANSFERIR DERECHOS SOBRE BIENES CONFORME A LO PREVISTO EN LA LEY 1152 DE 2007", label: "PROHIBICIÓN DE ENAJENAR O TRANSFERIR DERECHOS SOBRE BIENES CONFORME A LO PREVISTO EN LA LEY 1152 DE 2007" },
    { value: "ADMINISTRACIÓN ANTICRÉTICA", label: "ADMINISTRACIÓN ANTICRÉTICA" },
    { value: "ARRENDAMIENTO", label: "ARRENDAMIENTO" },
    { value: "COMODATO", label: "COMODATO" },
    { value: "COMODATO A TITULO PRECARIO", label: "COMODATO A TITULO PRECARIO" },
    { value: "CONSTITUCIÓN DE LEASING INMOBILIARIO", label: "CONSTITUCIÓN DE LEASING INMOBILIARIO" },
    { value: "ADJUDICACIÓN SUCESIÓN DERECHOS Y ACCIONES", label: "ADJUDICACIÓN SUCESIÓN DERECHOS Y ACCIONES" },
    { value: "ADJUDICACIÓN  SUCESIÓN GANANCIALES", label: "ADJUDICACIÓN  SUCESIÓN GANANCIALES" },
    { value: "AFECTACIÓN A VIVIENDA FAMILIAR SOBRE MEJORAS EN PREDIO AJENO.  PAR. ART. 5º LEY 258/96", label: "AFECTACIÓN A VIVIENDA FAMILIAR SOBRE MEJORAS EN PREDIO AJENO.  PAR. ART. 5º LEY 258/96" },
    { value: "COMPRAVENTA DE COSA AJENA", label: "COMPRAVENTA DE COSA AJENA" },
    { value: "COMPRAVENTA DE CUERPO CIERTO TENIENDO SOLO DERECHOS DE CUOTA CON ANTECEDENTE REGISTRAL", label: "COMPRAVENTA DE CUERPO CIERTO TENIENDO SOLO DERECHOS DE CUOTA CON ANTECEDENTE REGISTRAL" },
    { value: "COMPRAVENTA DERECHOS GANANCIALES", label: "COMPRAVENTA DERECHOS GANANCIALES" },
    { value: "COMPRAVENTA DERECHOS Y ACCIONES", label: "COMPRAVENTA DERECHOS Y ACCIONES" },
    { value: "COMPRAVENTA POSESIÓN CON ANTECEDENTE REGISTRAL", label: "COMPRAVENTA POSESIÓN CON ANTECEDENTE REGISTRAL" },
    { value: "DECLARACIÓN MEJORAS EN PREDIO AJENO. PAR. ART 5º LEY 258/96", label: "DECLARACIÓN MEJORAS EN PREDIO AJENO. PAR. ART 5º LEY 258/96" },
    { value: "DONACIÓN DERECHOS Y ACCIONES", label: "DONACIÓN DERECHOS Y ACCIONES" },
    { value: "DONACIÓN GANANCIALES", label: "DONACIÓN GANANCIALES" },
    { value: "PATRIMONIO DE FAMILIA SOBRE MEJORAS EN PREDIO AJENO. PAR. ART 5º LEY 258/96", label: "PATRIMONIO DE FAMILIA SOBRE MEJORAS EN PREDIO AJENO. PAR. ART 5º LEY 258/96" },
    { value: "REMATE DERECHOS Y ACCIONES", label: "REMATE DERECHOS Y ACCIONES" },
    { value: "REMATE GANANCIALES", label: "REMATE GANANCIALES" },
    { value: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD CONYUGAL DERECHOS Y ACCIONES", label: "ADJUDICACIÓN LIQUIDACIÓN SOCIEDAD CONYUGAL DERECHOS Y ACCIONES" },
    { value: "COMPRAVENTA MEJORAS SUELO AJENO CON ANTECEDENTE REGISTRAL", label: "COMPRAVENTA MEJORAS SUELO AJENO CON ANTECEDENTE REGISTRAL" },
    { value: "DACIÓN EN PAGO DE DERECHOS Y ACCIONES", label: "DACIÓN EN PAGO DE DERECHOS Y ACCIONES" },
    { value: "TRANSFERENCIA DE POSESIÓN CON ANTECEDENTE REGISTRAL", label: "TRANSFERENCIA DE POSESIÓN CON ANTECEDENTE REGISTRAL" },
    { value: "DECLARATORIA DE POSESIÓN REGULAR ART. 1 LEY 1183 DE 2008", label: "DECLARATORIA DE POSESIÓN REGULAR ART. 1 LEY 1183 DE 2008" },
    { value: "CANCELACIÓN ADMINISTRACIÓN ANTICRÉTICA", label: "CANCELACIÓN ADMINISTRACIÓN ANTICRÉTICA" },
    { value: "CANCELACIÓN AFECTACIÓN A VIVIENDA FAMILIAR", label: "CANCELACIÓN AFECTACIÓN A VIVIENDA FAMILIAR" },
    { value: "CANCELACIÓN AFECTACIÓN A VIVIENDA FAMILIAR SOBRE MEJORAS EN PREDIO AJENO POR .ART.5 LEY 258/96.", label: "CANCELACIÓN AFECTACIÓN A VIVIENDA FAMILIAR SOBRE MEJORAS EN PREDIO AJENO POR .ART.5 LEY 258/96." },
    { value: "CANCELACIÓN AFECTACIÓN POR CAUSA DE UNA OBRA PÚBLICA", label: "CANCELACIÓN AFECTACIÓN POR CAUSA DE UNA OBRA PÚBLICA" },
    { value: "CANCELACIÓN AMPLIACIÓN  DE HIPOTECA", label: "CANCELACIÓN AMPLIACIÓN  DE HIPOTECA" },
    { value: "CANCELACIÓN ARRENDAMIENTO", label: "CANCELACIÓN ARRENDAMIENTO" },
    { value: "CANCELACIÓN COMISO ESPECIAL", label: "CANCELACIÓN COMISO ESPECIAL" },
    { value: "CANCELACIÓN COMODATO", label: "CANCELACIÓN COMODATO" },
    { value: "CANCELACIÓN COMODATO A TITULO PRECARIO", label: "CANCELACIÓN COMODATO A TITULO PRECARIO" },
    { value: "CANCELACIÓN CONDICIÓN RESOLUTORIA EXPRESA", label: "CANCELACIÓN CONDICIÓN RESOLUTORIA EXPRESA" },
    { value: "CANCELACIÓN CONDICIÓN SUSPENSIVA", label: "CANCELACIÓN CONDICIÓN SUSPENSIVA" },
    { value: "CANCELACIÓN CONSTITUCIÓN  LEASING INMOBILIARIO", label: "CANCELACIÓN CONSTITUCIÓN  LEASING INMOBILIARIO" },
    { value: "CANCELACIÓN CONSTITUCIÓN DE FIDEICOMISO CIVIL", label: "CANCELACIÓN CONSTITUCIÓN DE FIDEICOMISO CIVIL" },
    { value: "CANCELACIÓN CONSTITUCIÓN DE MOVILIZACIÓN", label: "CANCELACIÓN CONSTITUCIÓN DE MOVILIZACIÓN" },
    { value: "CANCELACIÓN CONSTITUCIÓN DE URBANIZACIÓN", label: "CANCELACIÓN CONSTITUCIÓN DE URBANIZACIÓN" },
    { value: "CANCELACIÓN CONSTITUCIÓN DE USUFRUCTO", label: "CANCELACIÓN CONSTITUCIÓN DE USUFRUCTO" },
    { value: "CANCELACIÓN CONSTITUCIÓN FIDUCIA MERCANTIL", label: "CANCELACIÓN CONSTITUCIÓN FIDUCIA MERCANTIL" },
    { value: "CANCELACIÓN CONSTITUCIÓN PATRIMONIO DE FAMILIA", label: "CANCELACIÓN CONSTITUCIÓN PATRIMONIO DE FAMILIA" },
    { value: "CANCELACIÓN CONSTITUCIÓN RÉGIMEN DE CONDOMINIO", label: "CANCELACIÓN CONSTITUCIÓN RÉGIMEN DE CONDOMINIO" },
    { value: "CANCELACIÓN CONSTITUCIÓN REGLAMENTO DE PROPIEDAD HORIZONTAL", label: "CANCELACIÓN CONSTITUCIÓN REGLAMENTO DE PROPIEDAD HORIZONTAL" },
    { value: "CANCELACIÓN DE CONTRATO", label: "CANCELACIÓN DE CONTRATO" },
    { value: "CANCELACIÓN DE MEDIANERÍA", label: "CANCELACIÓN DE MEDIANERÍA" },
    { value: "CANCELACIÓN DE VALORIZACIÓN", label: "CANCELACIÓN DE VALORIZACIÓN" },
    { value: "CANCELACIÓN DECLARACIÓN MEJORA EN SUELO AJENO", label: "CANCELACIÓN DECLARACIÓN MEJORA EN SUELO AJENO" },
    { value: "CANCELACIÓN DECLARACIÓN MEJORAS EN PREDIO AJENO  PAR. ART. 5 LEY 258/96", label: "CANCELACIÓN DECLARACIÓN MEJORAS EN PREDIO AJENO  PAR. ART. 5 LEY 258/96" },
    { value: "CANCELACIÓN DECLARATORIA DE INDIVISIÓN", label: "CANCELACIÓN DECLARATORIA DE INDIVISIÓN" },
    { value: "CANCELACIÓN DECOMISO DE BIENES", label: "CANCELACIÓN DECOMISO DE BIENES" },
    { value: "CANCELACIÓN DEMANDA EN ACCIÓN DE SIMULACIÓN", label: "CANCELACIÓN DEMANDA EN ACCIÓN DE SIMULACIÓN" },
    { value: "CANCELACIÓN DEMANDA EN ACCIÓN REVOCATORIA", label: "CANCELACIÓN DEMANDA EN ACCIÓN REVOCATORIA" },
    { value: "CANCELACIÓN DEMANDA EN ACUERDO DE REESTRUCTURACIÓN", label: "CANCELACIÓN DEMANDA EN ACUERDO DE REESTRUCTURACIÓN" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE DECLARATORIA DE UNIÓN MARITAL DE HECHO", label: "CANCELACIÓN DEMANDA EN PROCESO DE DECLARATORIA DE UNIÓN MARITAL DE HECHO" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE DESLINDE Y AMOJONAMIENTO", label: "CANCELACIÓN DEMANDA EN PROCESO DE DESLINDE Y AMOJONAMIENTO" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE DIVORCIO", label: "CANCELACIÓN DEMANDA EN PROCESO DE DIVORCIO" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE PERTENENCIA", label: "CANCELACIÓN DEMANDA EN PROCESO DE PERTENENCIA" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE SEPARACIÓN DE BIENES", label: "CANCELACIÓN DEMANDA EN PROCESO DE SEPARACIÓN DE BIENES" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE SEPARACIÓN DE CUERPOS", label: "CANCELACIÓN DEMANDA EN PROCESO DE SEPARACIÓN DE CUERPOS" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DE SERVIDUMBRES", label: "CANCELACIÓN DEMANDA EN PROCESO DE SERVIDUMBRES" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO DIVISORIO", label: "CANCELACIÓN DEMANDA EN PROCESO DIVISORIO" },
    { value: "CANCELACIÓN DEMANDA ORDINARIA DE ENRIQUECIMIENTO SIN JUSTA CAUSA", label: "CANCELACIÓN DEMANDA ORDINARIA DE ENRIQUECIMIENTO SIN JUSTA CAUSA" },
    { value: "CANCELACIÓN DEMANDA POR EXPROPIACIÓN", label: "CANCELACIÓN DEMANDA POR EXPROPIACIÓN" },
    { value: "CANCELACIÓN DEMANDA POR INEFICACIA DEL ACUERDO DE REESTRUCTURACIÓN", label: "CANCELACIÓN DEMANDA POR INEFICACIA DEL ACUERDO DE REESTRUCTURACIÓN" },
    { value: "CANCELACIÓN DEMANDA ORDINARIA POR LESIÓN ENORME", label: "CANCELACIÓN DEMANDA ORDINARIA POR LESIÓN ENORME" },
    { value: "CANCELACIÓN DERECHO DE HABITACIÓN", label: "CANCELACIÓN DERECHO DE HABITACIÓN" },
    { value: "CANCELACIÓN DERECHO DE PREFERENCIA", label: "CANCELACIÓN DERECHO DE PREFERENCIA" },
    { value: "CANCELACIÓN DERECHO DE USO", label: "CANCELACIÓN DERECHO DE USO" },
    { value: "CANCELACIÓN DESTINACIÓN PROVISIONAL", label: "CANCELACIÓN DESTINACIÓN PROVISIONAL" },
    { value: "CANCELACIÓN EMBARGO CON ACCIÓN REAL", label: "CANCELACIÓN EMBARGO CON ACCIÓN REAL" },
    { value: "CANCELACIÓN EMBARGO CONCORDATORIO", label: "CANCELACIÓN EMBARGO CONCORDATORIO" },
    { value: "CANCELACIÓN EMBARGO DE ALIMENTOS", label: "CANCELACIÓN EMBARGO DE ALIMENTOS" },
    { value: "CANCELACIÓN EMBARGO DE BIENES Y HABERES DE PROPIEDAD DEL INTERVENIDO", label: "CANCELACIÓN EMBARGO DE BIENES Y HABERES DE PROPIEDAD DEL INTERVENIDO" },
    { value: "CANCELACIÓN EMBARGO DE LA SUCESIÓN", label: "CANCELACIÓN EMBARGO DE LA SUCESIÓN" },
    { value: "CANCELACIÓN EMBARGO DERECHOS Y ACCIONES POR GARANTÍA HIPOTECARIA", label: "CANCELACIÓN EMBARGO DERECHOS Y ACCIONES POR GARANTÍA HIPOTECARIA" },
    { value: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN MIXTA", label: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN MIXTA" },
    { value: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN PERSONAL", label: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN PERSONAL" },
    { value: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN PERSONAL DE DERECHOS Y ACCIONES", label: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN PERSONAL DE DERECHOS Y ACCIONES" },
    { value: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN PERSONAL DE GANANCIALES", label: "CANCELACIÓN EMBARGO EJECUTIVO CON ACCIÓN PERSONAL DE GANANCIALES" },
    { value: "CANCELACIÓN EMBARGO EJECUTIVO DERECHO DE CUOTA", label: "CANCELACIÓN EMBARGO EJECUTIVO DERECHO DE CUOTA" },
    { value: "CANCELACIÓN EMBARGO EN ACCIÓN DE SIMULACIÓN", label: "CANCELACIÓN EMBARGO EN ACCIÓN DE SIMULACIÓN" },
    { value: "CANCELACIÓN EMBARGO EN ACCIÓN REVOCATORIA", label: "CANCELACIÓN EMBARGO EN ACCIÓN REVOCATORIA" },
    { value: "CANCELACIÓN EMBARGO EN ACUERDO DE REESTRUCTURACIÓN", label: "CANCELACIÓN EMBARGO EN ACUERDO DE REESTRUCTURACIÓN" },
    { value: "CANCELACIÓN EMBARGO EN LIQUIDACIÓN OBLIGATORIA", label: "CANCELACIÓN EMBARGO EN LIQUIDACIÓN OBLIGATORIA" },
    { value: "CANCELACIÓN EMBARGO EN PROCESO  DE FISCALÍA", label: "CANCELACIÓN EMBARGO EN PROCESO  DE FISCALÍA" },
    { value: "CANCELACIÓN EMBARGO EN PROCESO DE DIVORCIO", label: "CANCELACIÓN EMBARGO EN PROCESO DE DIVORCIO" },
    { value: "CANCELACIÓN EMBARGO EN PROCESO DE SEPARACIÓN DE BIENES", label: "CANCELACIÓN EMBARGO EN PROCESO DE SEPARACIÓN DE BIENES" },
    { value: "CANCELACIÓN EMBARGO ESPECIAL ART. 66 CÓDIGO DE PROCEDIMIENTO PENAL", label: "CANCELACIÓN EMBARGO ESPECIAL ART. 66 CÓDIGO DE PROCEDIMIENTO PENAL" },
    { value: "CANCELACIÓN EMBARGO LABORAL", label: "CANCELACIÓN EMBARGO LABORAL" },
    { value: "CANCELACIÓN EMBARGO PENAL", label: "CANCELACIÓN EMBARGO PENAL" },
    { value: "CANCELACIÓN EMBARGO POR IMPUESTOS  MUNICIPALES", label: "CANCELACIÓN EMBARGO POR IMPUESTOS  MUNICIPALES" },
    { value: "CANCELACIÓN EMBARGO POR IMPUESTOS NACIONALES", label: "CANCELACIÓN EMBARGO POR IMPUESTOS NACIONALES" },
    { value: "CANCELACIÓN EMBARGO POR INEFICACIA DEL ACUERDO DE REESTRUCTURACIÓN", label: "CANCELACIÓN EMBARGO POR INEFICACIA DEL ACUERDO DE REESTRUCTURACIÓN" },
    { value: "CANCELACIÓN EMBARGO POR JURISDICCIÓN COACTIVA", label: "CANCELACIÓN EMBARGO POR JURISDICCIÓN COACTIVA" },
    { value: "CANCELACIÓN EMBARGO POR VALORIZACIÓN", label: "CANCELACIÓN EMBARGO POR VALORIZACIÓN" },
    { value: "CANCELACIÓN ESCRITURA", label: "CANCELACIÓN ESCRITURA" },
    { value: "CANCELACIÓN HIPOTECA", label: "CANCELACIÓN HIPOTECA" },
    { value: "CANCELACIÓN HIPOTECA ABIERTA", label: "CANCELACIÓN HIPOTECA ABIERTA" },
    { value: "CANCELACIÓN HIPOTECA CON CUANTÍA INDETERMINADA", label: "CANCELACIÓN HIPOTECA CON CUANTÍA INDETERMINADA" },
    { value: "CANCELACIÓN HIPOTECA DE BIENES EN USUFRUCTO", label: "CANCELACIÓN HIPOTECA DE BIENES EN USUFRUCTO" },
    { value: "CANCELACIÓN HIPOTECA DE MINAS CON ANTECEDENTE REGISTRAL", label: "CANCELACIÓN HIPOTECA DE MINAS CON ANTECEDENTE REGISTRAL" },
    { value: "CANCELACIÓN HIPOTECA DE UNIDAD AGRÍCOLA FAMILIAR", label: "CANCELACIÓN HIPOTECA DE UNIDAD AGRÍCOLA FAMILIAR" },
    { value: "CANCELACIÓN HIPOTECA DERECHOS DE CUOTA", label: "CANCELACIÓN HIPOTECA DERECHOS DE CUOTA" },
    { value: "CANCELACIÓN HIPOTECA DERECHOS Y ACCIONES", label: "CANCELACIÓN HIPOTECA DERECHOS Y ACCIONES" },
    { value: "CANCELACIÓN HIPOTECA GANANCIALES", label: "CANCELACIÓN HIPOTECA GANANCIALES" },
    { value: "CANCELACIÓN HIPOTECA RESPECTO DE ESTE INMUEBLE", label: "CANCELACIÓN HIPOTECA RESPECTO DE ESTE INMUEBLE" },
    { value: "CANCELACIÓN INICIACIÓN DEL PROCESO DE ENAJENACIÓN FORZOSA", label: "CANCELACIÓN INICIACIÓN DEL PROCESO DE ENAJENACIÓN FORZOSA" },
    { value: "CANCELACIÓN INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DE CLARIFICACIÓN DE LA PROPIEDAD", label: "CANCELACIÓN INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DE CLARIFICACIÓN DE LA PROPIEDAD" },
    { value: "CANCELACIÓN INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DESLINDE DE TIERRAS DE PROPIEDAD DE LA NACIÓN", label: "CANCELACIÓN INICIACIÓN DILIGENCIAS ADMINISTRATIVAS DESLINDE DE TIERRAS DE PROPIEDAD DE LA NACIÓN" },
    { value: "CANCELACIÓN INICIACIÓN DILIGENCIAS ADMINISTRATIVAS POR INDEBIDA OCUPACIÓN DE BALDÍOS", label: "CANCELACIÓN INICIACIÓN DILIGENCIAS ADMINISTRATIVAS POR INDEBIDA OCUPACIÓN DE BALDÍOS" },
    { value: "CANCELACIÓN INICIACIÓN PROCEDIMIENTO DE EXTINCIÓN DEL DERECHO DE DOMINIO", label: "CANCELACIÓN INICIACIÓN PROCEDIMIENTO DE EXTINCIÓN DEL DERECHO DE DOMINIO" },
    { value: "CANCELACIÓN INICIACIÓN PROCESO ADMINISTRATIVO DE ADQUISICIÓN", label: "CANCELACIÓN INICIACIÓN PROCESO ADMINISTRATIVO DE ADQUISICIÓN" },
    { value: "CANCELACIÓN INSCRIPCIÓN DEL PROCESO ARBITRAL", label: "CANCELACIÓN INSCRIPCIÓN DEL PROCESO ARBITRAL" },
    { value: "CANCELACIÓN MOVILIZACIÓN", label: "CANCELACIÓN MOVILIZACIÓN" },
    { value: "CANCELACIÓN OFERTA DE COMPRA BIEN RURAL", label: "CANCELACIÓN OFERTA DE COMPRA BIEN RURAL" },
    { value: "CANCELACIÓN OFERTA DE COMPRA BIEN URBANO", label: "CANCELACIÓN OFERTA DE COMPRA BIEN URBANO" },
    { value: "CANCELACIÓN PACTO COMISORIO", label: "CANCELACIÓN PACTO COMISORIO" },
    { value: "CANCELACIÓN PACTO DE INDIVISIÓN", label: "CANCELACIÓN PACTO DE INDIVISIÓN" },
    { value: "CANCELACIÓN PACTO DE RETROVENTA", label: "CANCELACIÓN PACTO DE RETROVENTA" },
    { value: "CANCELACIÓN PACTO RESERVA DE DOMINIO", label: "CANCELACIÓN PACTO RESERVA DE DOMINIO" },
    { value: "CANCELACIÓN PATRIMONIO DE FAMILIA SOBRE MEJORAS EN PREDIO AJENO PAR. ART. 5 LEY 258/96", label: "CANCELACIÓN PATRIMONIO DE FAMILIA SOBRE MEJORAS EN PREDIO AJENO PAR. ART. 5 LEY 258/96" },
    { value: "CANCELACIÓN PREVENCIÓN NO PROCEDE LA REALIZACIÓN DE NUEVOS EMBARGOS SOBRE BIENES DE LA INTERVENIDA", label: "CANCELACIÓN PREVENCIÓN NO PROCEDE LA REALIZACIÓN DE NUEVOS EMBARGOS SOBRE BIENES DE LA INTERVENIDA" },
    { value: "CANCELACIÓN PROHIBICIÓN CANCELAR GRAVÁMENES CONSTITUIDOS A FAVOR DE INTERVENIDA SALVO AUTORIZACIÓN LIQUIDADOR", label: "CANCELACIÓN PROHIBICIÓN CANCELAR GRAVÁMENES CONSTITUIDOS A FAVOR DE INTERVENIDA SALVO AUTORIZACIÓN LIQUIDADOR" },
    { value: "CANCELACIÓN PROHIBICIÓN ADMINISTRATIVA", label: "CANCELACIÓN PROHIBICIÓN ADMINISTRATIVA" },
    { value: "CANCELACIÓN PROHIBICIÓN DE ENAJENAR SIN AUTORIZACIÓN", label: "CANCELACIÓN PROHIBICIÓN DE ENAJENAR SIN AUTORIZACIÓN" },
    { value: "CANCELACIÓN PROHIBICIÓN GRAVAR, CEDER, LIMITAR O ARRENDAR SIN AUTORIZACIÓN", label: "CANCELACIÓN PROHIBICIÓN GRAVAR, CEDER, LIMITAR O ARRENDAR SIN AUTORIZACIÓN" },
    { value: "CANCELACIÓN PROHIBICIÓN INSCRIPCIÓN ACTOS AFECTEN DOMINIO DE BIENES INTERVENIDA SALVO LO REALIZADO POR AGENTE ESPECIAL", label: "CANCELACIÓN PROHIBICIÓN INSCRIPCIÓN ACTOS AFECTEN DOMINIO DE BIENES INTERVENIDA SALVO LO REALIZADO POR AGENTE ESPECIAL" },
    { value: "CANCELACIÓN PROHIBICIÓN JUDICIAL", label: "CANCELACIÓN PROHIBICIÓN JUDICIAL" },
    { value: "CANCELACIÓN PROHIBICIÓN REGISTRO ACTOS AFECTEN DOMINIO BIENES PROPIEDAD DE INTERVENIDA  SALVO AUTORIZACIÓN LIQUIDADOR", label: "CANCELACIÓN PROHIBICIÓN REGISTRO ACTOS AFECTEN DOMINIO BIENES PROPIEDAD DE INTERVENIDA  SALVO AUTORIZACIÓN LIQUIDADOR" },
    { value: "CANCELACIÓN PROHIBICIÓN REMATAR, ADJUDICAR, ENAJENAR A CUALQUIER TITULO BIENES DEL GARANTE", label: "CANCELACIÓN PROHIBICIÓN REMATAR, ADJUDICAR, ENAJENAR A CUALQUIER TITULO BIENES DEL GARANTE" },
    { value: "CANCELACIÓN REFORMA RÉGIMEN DE CONDOMINIO", label: "CANCELACIÓN REFORMA RÉGIMEN DE CONDOMINIO" },
    { value: "CANCELACIÓN REFORMA REGLAMENTO DE PROPIEDAD HORIZONTAL", label: "CANCELACIÓN REFORMA REGLAMENTO DE PROPIEDAD HORIZONTAL" },
    { value: "CANCELACIÓN RESERVA DERECHO DE USUFRUCTO", label: "CANCELACIÓN RESERVA DERECHO DE USUFRUCTO" },
    { value: "CANCELACIÓN SERVIDUMBRE DE ACUEDUCTO ACTIVA", label: "CANCELACIÓN SERVIDUMBRE DE ACUEDUCTO ACTIVA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE ACUEDUCTO PASIVA", label: "CANCELACIÓN SERVIDUMBRE DE ACUEDUCTO PASIVA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE AGUAS NEGRAS ACTIVA", label: "CANCELACIÓN SERVIDUMBRE DE AGUAS NEGRAS ACTIVA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE AGUAS NEGRAS PASIVA", label: "CANCELACIÓN SERVIDUMBRE DE AGUAS NEGRAS PASIVA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE AIRE", label: "CANCELACIÓN SERVIDUMBRE DE AIRE" },
    { value: "CANCELACIÓN SERVIDUMBRE DE ENERGÍA ELÉCTRICA", label: "CANCELACIÓN SERVIDUMBRE DE ENERGÍA ELÉCTRICA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE GASODUCTO", label: "CANCELACIÓN SERVIDUMBRE DE GASODUCTO" },
    { value: "CANCELACIÓN SERVIDUMBRE DE LUZ", label: "CANCELACIÓN SERVIDUMBRE DE LUZ" },
    { value: "CANCELACIÓN SERVIDUMBRE DE OLEODUCTO", label: "CANCELACIÓN SERVIDUMBRE DE OLEODUCTO" },
    { value: "CANCELACIÓN SERVIDUMBRE DE TRANSITO ACTIVA", label: "CANCELACIÓN SERVIDUMBRE DE TRANSITO ACTIVA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE TRANSITO PASIVA", label: "CANCELACIÓN SERVIDUMBRE DE TRANSITO PASIVA" },
    { value: "CANCELACIÓN AFECTACIÓN POR CAUSA DE CATEGORÍAS AMBIENTALES", label: "CANCELACIÓN AFECTACIÓN POR CAUSA DE CATEGORÍAS AMBIENTALES" },
    { value: "CANCELACIÓN TOMA DE POSESIÓN INMEDIATA DE BIENES HABERES Y NEGOCIOS DE ENTIDAD VIGILADA", label: "CANCELACIÓN TOMA DE POSESIÓN INMEDIATA DE BIENES HABERES Y NEGOCIOS DE ENTIDAD VIGILADA" },
    { value: "RESTABLECIMIENTO DE LA EXIGIBILIDAD DE GRAVÁMENES Y GARANTÍAS REALES Y FIDUCIARIAS", label: "RESTABLECIMIENTO DE LA EXIGIBILIDAD DE GRAVÁMENES Y GARANTÍAS REALES Y FIDUCIARIAS" },
    { value: "CANCELACIÓN ADICIÓN RÉGIMEN DE CONDOMINIO", label: "CANCELACIÓN ADICIÓN RÉGIMEN DE CONDOMINIO" },
    { value: "CANCELACIÓN ADICIÓN RÉGIMEN DE PROPIEDAD HORIZONTAL", label: "CANCELACIÓN ADICIÓN RÉGIMEN DE PROPIEDAD HORIZONTAL" },
    { value: "CANCELACIÓN DEMANDA DE ACCIÓN DE PETICIÓN DE HERENCIA", label: "CANCELACIÓN DEMANDA DE ACCIÓN DE PETICIÓN DE HERENCIA" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO ORDINARIO", label: "CANCELACIÓN DEMANDA EN PROCESO ORDINARIO" },
    { value: "CANCELACIÓN DEMANDA EN PROCESO REIVINDICATORIO", label: "CANCELACIÓN DEMANDA EN PROCESO REIVINDICATORIO" },
    { value: "CANCELACIÓN HIPOTECA NUDA PROPIEDAD", label: "CANCELACIÓN HIPOTECA NUDA PROPIEDAD" },
    { value: "CANCELACIÓN SERVIDUMBRE DE AGUA ACTIVA", label: "CANCELACIÓN SERVIDUMBRE DE AGUA ACTIVA" },
    { value: "CANCELACIÓN SERVIDUMBRE DE AGUA PASIVA", label: "CANCELACIÓN SERVIDUMBRE DE AGUA PASIVA" },
    { value: "EXTINCIÓN PARCIAL RÉGIMEN DE CONDOMINIO", label: "EXTINCIÓN PARCIAL RÉGIMEN DE CONDOMINIO" },
    { value: "EXTINCIÓN PARCIAL RÉGIMEN DE PROPIEDAD HORIZONTAL", label: "EXTINCIÓN PARCIAL RÉGIMEN DE PROPIEDAD HORIZONTAL" },
    { value: "EXTINCIÓN TOTAL RÉGIMEN DE CONDOMINIO", label: "EXTINCIÓN TOTAL RÉGIMEN DE CONDOMINIO" },
    { value: "EXTINCIÓN TOTAL RÉGIMEN DE PROPIEDAD HORIZONTAL", label: "EXTINCIÓN TOTAL RÉGIMEN DE PROPIEDAD HORIZONTAL" },
    { value: "LEVANTAMIENTO DE IMPEDIMENTO A LA LIBRE ENAJENACIÓN, TRANSFERENCIA O TITULACIÓN DE BIENES RURALES", label: "LEVANTAMIENTO DE IMPEDIMENTO A LA LIBRE ENAJENACIÓN, TRANSFERENCIA O TITULACIÓN DE BIENES RURALES" },
    { value: "CANCELACIÓN DECLARATORIA ZONA DE RIESGO INMINENTE DE DESPLAZAMIENTO", label: "CANCELACIÓN DECLARATORIA ZONA DE RIESGO INMINENTE DE DESPLAZAMIENTO" },
    { value: "CANCELACIÓN DECLARATORIA ZONA DE DESPLAZAMIENTO FORZADO", label: "CANCELACIÓN DECLARATORIA ZONA DE DESPLAZAMIENTO FORZADO" },
    { value: "ACLARACIÓN", label: "ACLARACIÓN" },
    { value: "ACTUALIZACIÓN ÁREA", label: "ACTUALIZACIÓN ÁREA" },
    { value: "ACTUALIZACIÓN DE LINDEROS", label: "ACTUALIZACIÓN DE LINDEROS" },
    { value: "ACTUALIZACIÓN DE NOMENCLATURA", label: "ACTUALIZACIÓN DE NOMENCLATURA" },
    { value: "AUTORIZACIÓN  REGISTRO", label: "AUTORIZACIÓN  REGISTRO" },
    { value: "CAMBIO DE NOMBRE", label: "CAMBIO DE NOMBRE" },
    { value: "CAMBIO DE RAZÓN SOCIAL", label: "CAMBIO DE RAZÓN SOCIAL" },
    { value: "CONFIRMACIÓN SENTENCIA", label: "CONFIRMACIÓN SENTENCIA" },
    { value: "CONSTITUCIÓN DE URBANIZACIÓN", label: "CONSTITUCIÓN DE URBANIZACIÓN" },
    { value: "DECLARACIÓN DE CONSTRUCCIÓN CON SUBSIDIO FAMILIAR DE VIVIENDA", label: "DECLARACIÓN DE CONSTRUCCIÓN CON SUBSIDIO FAMILIAR DE VIVIENDA" },
    { value: "DECLARACIÓN DE CONSTRUCCIÓN EN SUELO PROPIO", label: "DECLARACIÓN DE CONSTRUCCIÓN EN SUELO PROPIO" },
    { value: "DECLARACIÓN DE MEJORAS EN SUELO PROPIO", label: "DECLARACIÓN DE MEJORAS EN SUELO PROPIO" },
    { value: "DECLARACIÓN PARTE RESTANTE", label: "DECLARACIÓN PARTE RESTANTE" },
    { value: "DELIMITACIÓN UNIDAD DE ACTUACIÓN URBANÍSTICA", label: "DELIMITACIÓN UNIDAD DE ACTUACIÓN URBANÍSTICA" },
    { value: "DESENGLOBE", label: "DESENGLOBE" },
    { value: "DESLINDE DE TERRENO DE PROPIEDAD DE LA NACIÓN", label: "DESLINDE DE TERRENO DE PROPIEDAD DE LA NACIÓN" },
    { value: "DETERMINACIÓN ÁREA Y LINDEROS PREDIO DEL MUNICIPIO", label: "DETERMINACIÓN ÁREA Y LINDEROS PREDIO DEL MUNICIPIO" },
    { value: "DIVISIÓN MATERIAL", label: "DIVISIÓN MATERIAL" },
    { value: "ENGLOBE", label: "ENGLOBE" },
    { value: "LOTEO", label: "LOTEO" },
    { value: "PERMISO CONSTITUIR GRAVAMEN", label: "PERMISO CONSTITUIR GRAVAMEN" },
    { value: "PERMISO VENTA", label: "PERMISO VENTA" },
    { value: "REGLAMENTACIÓN URBANÍSTICA ESPECIAL", label: "REGLAMENTACIÓN URBANÍSTICA ESPECIAL" },
    { value: "RELOTEO", label: "RELOTEO" },
    { value: "DECLARACIÓN EXTINCIÓN OBLIGACIÓN HIPOTECARIA", label: "DECLARACIÓN EXTINCIÓN OBLIGACIÓN HIPOTECARIA" },
    { value: "AUTORIZACIÓN CAMBIO DE DESTINACIÓN Y SUSTRACCIÓN DEL RÉGIMEN DE UNIDAD AGRÍCOLA FAMILIAR", label: "AUTORIZACIÓN CAMBIO DE DESTINACIÓN Y SUSTRACCIÓN DEL RÉGIMEN DE UNIDAD AGRÍCOLA FAMILIAR" },
    { value: "VENTA", label: "VENTA" },
    { value: "PODER GENERAL", label: "PODER GENERAL" },
    { value: "AUTORIZACION PARA SALIR DEL PAIS A MENOR DE EDAD", label: "AUTORIZACION PARA SALIR DEL PAIS A MENOR DE EDAD" },
    { value: "CORRECCIÓN REGISTRO CIVIL DE NACIMIENTO", label: "CORRECCIÓN REGISTRO CIVIL DE NACIMIENTO" },
    { value: "CAPITULACIONES MATRIMONIALES", label: "CAPITULACIONES MATRIMONIALES" },
    { value: "HIPOTECA ABIERTA EN PRIMER GRADO SIN LÍMITE DE CUANTÍA", label: "HIPOTECA ABIERTA EN PRIMER GRADO SIN LÍMITE DE CUANTÍA" },
    { value: "PODER", label: "PODER" },
    { value: "CORRECCIÓN REGISTRO CIVIL DE NACIMIENTO ADULTO", label: "CORRECCIÓN REGISTRO CIVIL DE NACIMIENTO ADULTO" },
    { value: "VENTA DE DERECHO A GANANCIALES A TITULO UNIVERSAL", label: "VENTA DE DERECHO A GANANCIALES A TITULO UNIVERSAL" },
    { value: "VENTA DE CUOTA O 50%", label: "VENTA DE CUOTA O 50%" },
  ],
  "DEPARTAMENTO": [
    { value: "Amazonas", label: "Amazonas" },
    { value: "Antioquia", label: "Antioquia" },
    { value: "Arauca", label: "Arauca" },
    { value: "Atlántico", label: "Atlántico" },
    { value: "Bolívar", label: "Bolívar" },
    { value: "Boyacá", label: "Boyacá" },
    { value: "Caldas", label: "Caldas" },
    { value: "Caquetá", label: "Caquetá" },
    { value: "Casanare", label: "Casanare" },
    { value: "Cauca", label: "Cauca" },
    { value: "Cesar", label: "Cesar" },
    { value: "Chocó", label: "Chocó" },
    { value: "Córdoba", label: "Córdoba" },
    { value: "Cundinamarca", label: "Cundinamarca" },
    { value: "Guainía", label: "Guainía" },
    { value: "Guaviare", label: "Guaviare" },
    { value: "Huila", label: "Huila" },
    { value: "La Guajira", label: "La Guajira" },
    { value: "Magdalena", label: "Magdalena" },
    { value: "Meta", label: "Meta" },
    { value: "Nariño", label: "Nariño" },
    { value: "Norte de Santander", label: "Norte de Santander" },
    { value: "Putumayo", label: "Putumayo" },
    { value: "Quindío", label: "Quindío" },
    { value: "Risaralda", label: "Risaralda" },
    { value: "San Andrés y Providencia", label: "San Andrés y Providencia" },
    { value: "Santander", label: "Santander" },
    { value: "Sucre", label: "Sucre" },
    { value: "Tolima", label: "Tolima" },
    { value: "Valle del Cauca", label: "Valle del Cauca" },
    { value: "Vaupés", label: "Vaupés" },
    { value: "Vichada", label: "Vichada" },
  ],
  "CIRCULO NOTARIAL": [
    { value: "Notaria primera (1a) de Medellín,", label: "Notaria primera (1a) de Medellín," },
    { value: "Notaria segunda (2a) de Medellín,", label: "Notaria segunda (2a) de Medellín," },
    { value: "Notaria tercera (3a) de Medellín,", label: "Notaria tercera (3a) de Medellín," },
    { value: "Notaria cuarta (4ta) de Medellín,", label: "Notaria cuarta (4ta) de Medellín," },
    { value: "Notaria quinta (5ta) de Medellín,", label: "Notaria quinta (5ta) de Medellín," },
    { value: "Notaria sexta (6ta) de Medellín,", label: "Notaria sexta (6ta) de Medellín," },
    { value: "Notaria séptima (7a) de Medellín,", label: "Notaria séptima (7a) de Medellín," },
    { value: "Notaria octava (8) de Medellín,", label: "Notaria octava (8) de Medellín," },
    { value: "Notaria novena (9na) de Medellín,", label: "Notaria novena (9na) de Medellín," },
    { value: "Notaria décima (10) de Medellín,", label: "Notaria décima (10) de Medellín," },
    { value: "Notaria once (11) de Medellín,", label: "Notaria once (11) de Medellín," },
    { value: "Notaria doce (12) de Medellín,", label: "Notaria doce (12) de Medellín," },
    { value: "Notaria trece (13) de Medellín,", label: "Notaria trece (13) de Medellín," },
    { value: "Notaria catorce (14) de Medellín,", label: "Notaria catorce (14) de Medellín," },
    { value: "Notaria quince (15) de Medellín,", label: "Notaria quince (15) de Medellín," },
    { value: "Notaria dieciseis (16) de Medellín,", label: "Notaria dieciseis (16) de Medellín," },
    { value: "Notaria diecisiete (17) de Medellín,", label: "Notaria diecisiete (17) de Medellín," },
    { value: "Notaria dieciocho (18) de Medellín,", label: "Notaria dieciocho (18) de Medellín," },
    { value: "Notaria diecinueve (19) de Medellín,", label: "Notaria diecinueve (19) de Medellín," },
    { value: "Notaria veinte (20) de Medellín,", label: "Notaria veinte (20) de Medellín," },
    { value: "Notaria veintiuno (21) de Medellín,", label: "Notaria veintiuno (21) de Medellín," },
    { value: "Notaria veintidos (22) de Medellín,", label: "Notaria veintidos (22) de Medellín," },
    { value: "Notaria veintitres (23) de Medellín,", label: "Notaria veintitres (23) de Medellín," },
    { value: "Notaria veinticuatro (24) de Medellín,", label: "Notaria veinticuatro (24) de Medellín," },
    { value: "Notaria veinticinco (25) de Medellín,", label: "Notaria veinticinco (25) de Medellín," },
    { value: "Notaria veintiseis (26) de Medellín,", label: "Notaria veintiseis (26) de Medellín," },
    { value: "Notaria veintisiete (27) de Medellín,", label: "Notaria veintisiete (27) de Medellín," },
    { value: "Notaria veintiocho (28) de Medellín,", label: "Notaria veintiocho (28) de Medellín," },
    { value: "Notaria veintinueve (29) de Medellín,", label: "Notaria veintinueve (29) de Medellín," },
    { value: "Notaria treinta (30) de Medellín,", label: "Notaria treinta (30) de Medellín," },
    { value: "Notaria treinta y uno (31) de Medellín,", label: "Notaria treinta y uno (31) de Medellín," },
    { value: "Notaria primera (1a) de bello", label: "Notaria primera (1a) de bello" },
    { value: "Notaria segunda (2da) de Bello", label: "Notaria segunda (2da) de Bello" },
    { value: "Notaria tercera (3a) de Bello", label: "Notaria tercera (3a) de Bello" },
    { value: "Registraduría Nacional del Estado Civil", label: "Registraduría Nacional del Estado Civil" },
    { value: "Alcadía de Montelíbano", label: "Alcadía de Montelíbano" },
    { value: "Notaría Única del Círculo de Caldas, Antioquia", label: "Notaría Única del Círculo de Caldas, Antioquia" },
  ],
  "AÑO": [
    { value: "dos mil veinticuatro (2024)", label: "dos mil veinticuatro (2024)" },
    { value: "dos mil veinticinco (2025)", label: "dos mil veinticinco (2025)" },
  ],
  "PROTOCOLISTA": [
    { value: "PAOLA HENAO PULGARÍN", label: "PAOLA HENAO PULGARÍN" },
    { value: "Maria I", label: "Maria I" },
    { value: "Tatiana", label: "Tatiana" },
  ],
  "NOTA LINDEROS": [
    { value: "A solicitud y ruego de los otorgantes, se procedió a efectuar en este instrumento la transcripción de los linderos del bien objeto de este contrato", label: "A solicitud y ruego de los otorgantes, se procedió a efectuar en este instrumento la transcripción de los linderos del bien objeto de este contrato" },
    { value: "Por no estar descrito(s) lo(s) lindero(s) de lo(s) biene(s) inmueble(s) objeto del presente acto, en el certificado de tradición y libertad, se procede a transcribirlos, dando cumplimiento a lo orientado por la instrucción administrativa No. 01 del 13-04-2016 de la Superintendencia de Notariado y Registro", label: "Por no estar descrito(s) lo(s) lindero(s) de lo(s) biene(s) inmueble(s) objeto del presente acto, en el certificado de tradición y libertad, se procede a transcribirlos, dando cumplimiento a lo orientado por la instrucción administrativa No. 01 del 13-04-2016 de la Superintendencia de Notariado y Registro" },
  ],
  "OFICINA_REGISTRO": [
    { value: "Medellín, zona norte", label: "Medellín, zona norte" },
    { value: "Montelíbano", label: "Montelíbano" },
  ],
  "DE TRANSITO": [
    { value: "de tránsito por este municipio de Caldas, Antioquia,", label: "de tránsito por este municipio de Caldas, Antioquia," },
  ],
  "ARTICULO 6 AFECTACION": [
    { value: "no tiene(n) ningún", label: "no tiene(n) ningún" },
    { value: "si tiene(n) un", label: "si tiene(n) un" },
  ],
  "TIPO MATRIMONIO": [
    { value: "civil", label: "civil" },
    { value: "católico", label: "católico" },
  ],
  "RESOLUCION DE ADQUISICION": [
    { value: "Escritura Pública", label: "Escritura Pública" },
    { value: "Resolución Administrativa", label: "Resolución Administrativa" },
  ],
  "PAIS": [
    { value: "España", label: "España" },
    { value: "Afganistán", label: "Afganistán" },
    { value: "Albania", label: "Albania" },
    { value: "Alemania", label: "Alemania" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Antigua y Barbuda", label: "Antigua y Barbuda" },
    { value: "Arabia Saudita", label: "Arabia Saudita" },
    { value: "Argelia", label: "Argelia" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaiyán", label: "Azerbaiyán" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bangladés", label: "Bangladés" },
    { value: "Barbados", label: "Barbados" },
    { value: "Baréin", label: "Baréin" },
    { value: "Bélgica", label: "Bélgica" },
    { value: "Belice", label: "Belice" },
    { value: "Benín", label: "Benín" },
    { value: "Bielorrusia", label: "Bielorrusia" },
    { value: "Birmania", label: "Birmania" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia y Herzegobina", label: "Bosnia y Herzegobina" },
    { value: "Botsuana", label: "Botsuana" },
    { value: "Brasil", label: "Brasil" },
    { value: "Brunéi", label: "Brunéi" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Bután", label: "Bután" },
    { value: "Cabo Verde", label: "Cabo Verde" },
    { value: "Camboya", label: "Camboya" },
    { value: "Camerún", label: "Camerún" },
    { value: "Canadá", label: "Canadá" },
    { value: "Catar", label: "Catar" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Chipre", label: "Chipre" },
    { value: "Ciudad del Vaticano", label: "Ciudad del Vaticano" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoras", label: "Comoras" },
    { value: "Corea del Norte", label: "Corea del Norte" },
    { value: "Corea del Sur", label: "Corea del Sur" },
    { value: "Costa de Marfil", label: "Costa de Marfil" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Croacia", label: "Croacia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Dinamarca", label: "Dinamarca" },
    { value: "Dominica", label: "Dominica" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egipto", label: "Egipto" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Emiratos Árabes Unidos", label: "Emiratos Árabes Unidos" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Eslovaquia", label: "Eslovaquia" },
    { value: "Eslovenia", label: "Eslovenia" },
    { value: "Estados Unidos", label: "Estados Unidos" },
    { value: "Estonia", label: "Estonia" },
    { value: "Etiopía", label: "Etiopía" },
    { value: "Filipinas", label: "Filipinas" },
    { value: "Finlandia", label: "Finlandia" },
    { value: "Fiyi", label: "Fiyi" },
    { value: "Francia", label: "Francia" },
    { value: "Gabón", label: "Gabón" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Ghana", label: "Ghana" },
    { value: "Granada", label: "Granada" },
    { value: "Grecia", label: "Grecia" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guyana", label: "Guyana" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea Ecuatorial", label: "Guinea Ecuatorial" },
    { value: "Guinea-Bisáu", label: "Guinea-Bisáu" },
    { value: "Haití", label: "Haití" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hungría", label: "Hungría" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Irak", label: "Irak" },
    { value: "Irán", label: "Irán" },
    { value: "Irlanda", label: "Irlanda" },
    { value: "Islandia", label: "Islandia" },
    { value: "Islas Marshall", label: "Islas Marshall" },
    { value: "Islas Salomón", label: "Islas Salomón" },
    { value: "Israel", label: "Israel" },
    { value: "Italia", label: "Italia" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japón", label: "Japón" },
    { value: "Jordania", label: "Jordania" },
    { value: "Kazajistán", label: "Kazajistán" },
    { value: "Kenia", label: "Kenia" },
    { value: "kirguistán", label: "kirguistán" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Laos", label: "Laos" },
    { value: "Lesoto", label: "Lesoto" },
    { value: "Letonia", label: "Letonia" },
    { value: "Líbano", label: "Líbano" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libia", label: "Libia" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lituania", label: "Lituania" },
    { value: "Luxemburgo", label: "Luxemburgo" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malasia", label: "Malasia" },
    { value: "Malaui", label: "Malaui" },
    { value: "Maldivas", label: "Maldivas" },
    { value: "Malí", label: "Malí" },
    { value: "Malta", label: "Malta" },
    { value: "Marruecos", label: "Marruecos" },
    { value: "Mauricio", label: "Mauricio" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "México", label: "México" },
    { value: "Micronesia", label: "Micronesia" },
    { value: "Moldavia", label: "Moldavia" },
    { value: "Mónaco", label: "Mónaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Noruega", label: "Noruega" },
    { value: "Nueva Zelanda", label: "Nueva Zelanda" },
    { value: "Omán", label: "Omán" },
    { value: "Países Bajos", label: "Países Bajos" },
    { value: "Pakistán", label: "Pakistán" },
    { value: "Palaos", label: "Palaos" },
    { value: "Panamá", label: "Panamá" },
    { value: "Papúa Nueva Guinea", label: "Papúa Nueva Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Perú", label: "Perú" },
    { value: "Polonia", label: "Polonia" },
    { value: "Portugal", label: "Portugal" },
    { value: "Reino Unido", label: "Reino Unido" },
    { value: "República Centroafricana", label: "República Centroafricana" },
    { value: "República Checa", label: "República Checa" },
    { value: "República de Macedonia", label: "República de Macedonia" },
    { value: "República del Congo", label: "República del Congo" },
    { value: "República Democrática del Congo", label: "República Democrática del Congo" },
    { value: "República Dominicana", label: "República Dominicana" },
    { value: "República Sudafricana", label: "República Sudafricana" },
    { value: "Ruanda", label: "Ruanda" },
    { value: "Rumanía", label: "Rumanía" },
    { value: "Rusia", label: "Rusia" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Cristóbal y Nieves", label: "San Cristóbal y Nieves" },
    { value: "San Marino", label: "San Marino" },
    { value: "San Vicente y las Granadinas", label: "San Vicente y las Granadinas" },
    { value: "Santa Lucia", label: "Santa Lucia" },
    { value: "Santo Tomé y Príncipe", label: "Santo Tomé y Príncipe" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leona", label: "Sierra Leona" },
    { value: "Singapur", label: "Singapur" },
    { value: "Siria", label: "Siria" },
    { value: "Somalia", label: "Somalia" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Suazilandia", label: "Suazilandia" },
    { value: "Sudán", label: "Sudán" },
    { value: "Sudán de Sur", label: "Sudán de Sur" },
    { value: "Suecia", label: "Suecia" },
    { value: "Suiza", label: "Suiza" },
    { value: "Surinam", label: "Surinam" },
    { value: "Tailandia", label: "Tailandia" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Tayikistán", label: "Tayikistán" },
    { value: "Timor Oriental", label: "Timor Oriental" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad y Tobago", label: "Trinidad y Tobago" },
    { value: "Túnez", label: "Túnez" },
    { value: "Turkmenistán", label: "Turkmenistán" },
    { value: "Turquía", label: "Turquía" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Ucrania", label: "Ucrania" },
    { value: "Uganda", label: "Uganda" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistán", label: "Uzbekistán" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Yemen", label: "Yemen" },
    { value: "Yibuti", label: "Yibuti" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
  ],
  "CUOTA INICIAL": [
    { value: "subsidio de vivienda", label: "subsidio de vivienda" },
    { value: "recursos propios", label: "recursos propios" },
    { value: "ahorros programados", label: "ahorros programados" },
    { value: "cesantías", label: "cesantías" },
  ],
  "SI O NO": [
    { value: "SI", label: "SI" },
    { value: "NO", label: "NO" },
  ],
  "PATRIMONIO DE FAMILIA": [
    { value: "de su cónyuge,", label: "de su cónyuge," },
    { value: "de su compañero permanente,", label: "de su compañero permanente," },
  ],
  "DIAS": [
    { value: "XXX", label: "XXX" },
  ],
  "PADRES": [
    { value: "Padre", label: "Padre" },
    { value: "Madre", label: "Madre" },
  ],
};

const EASYPRO1_NOTARIAL_CATALOG_INDEX: Record<string, string[]> = {
  "TIPO DE DOCUMENTO": ["TIPO DE DOCUMENTO"],
  "SEXO": ["SEXO"],
  "NOTARIO": ["NOTARIO"],
  "MES": ["MES"],
  "NACIONALIDAD": ["NACIONALIDAD"],
  "GENERO": ["GENERO"],
  "DIAS": ["DÍAS", "DIAS"],
  "ESTADO CIVIL": ["ESTADO CIVIL"],
  "MUNICIPIO": ["MUNICIPIO"],
  "ACTOS": ["ACTOS"],
  "DEPARTAMENTO": ["DEPARTAMENTO"],
  "CIRCULO NOTARIAL": ["CIRCULO NOTARIAL"],
  "ANO": ["AÑO"],
  "PROTOCOLISTA": ["PROTOCOLISTA"],
  "NOTA LINDEROS": ["NOTA LINDEROS"],
  "OFICINA_REGISTRO": ["OFICINA_REGISTRO"],
  "DE TRANSITO": ["DE TRANSITO"],
  "ARTICULO 6 AFECTACION": ["ARTICULO 6 AFECTACION"],
  "TIPO MATRIMONIO": ["TIPO MATRIMONIO"],
  "RESOLUCION DE ADQUISICION": ["RESOLUCION DE ADQUISICION"],
  "PAIS": ["PAIS"],
  "CUOTA INICIAL": ["CUOTA INICIAL"],
  "SI O NO": ["SI O NO"],
  "PATRIMONIO DE FAMILIA": ["PATRIMONIO DE FAMILIA"],
  "PADRES": ["PADRES"],
};

function normalizeCatalogName(catalogName: string) {
  return catalogName
    .trim()
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function getEasyPro1CatalogOptions(catalogName: string): NotarialCatalogOption[] {
  if (!catalogName) {
    return [];
  }

  const exact = EASYPRO1_NOTARIAL_CATALOGS[catalogName];
  if (exact) {
    return exact;
  }

  const normalized = normalizeCatalogName(catalogName);
  if (!normalized) {
    return [];
  }

  const directMatch = Object.keys(EASYPRO1_NOTARIAL_CATALOGS).find((key) => normalizeCatalogName(key) === normalized);
  if (directMatch) {
    return EASYPRO1_NOTARIAL_CATALOGS[directMatch];
  }

  const catalogNames = EASYPRO1_NOTARIAL_CATALOG_INDEX[normalized];
  if (!catalogNames?.length) {
    return [];
  }

  const seen = new Set<string>();
  const options: NotarialCatalogOption[] = [];
  for (const name of catalogNames) {
    for (const option of EASYPRO1_NOTARIAL_CATALOGS[name] ?? []) {
      if (seen.has(option.value)) {
        continue;
      }
      seen.add(option.value);
      options.push(option);
    }
  }
  return options;
}
